/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Hashtable;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Thusitha
 */
public class AddLevel extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddLevel
     */
    public AddLevel() {
        initComponents();
        Hashtable sliderLable = new Hashtable();
        sliderLable.put(new Integer(0), new JLabel("Guest"));
        sliderLable.put(new Integer(25), new JLabel("Cashier"));
        sliderLable.put(new Integer(50), new JLabel("Stock Handler"));
        sliderLable.put(new Integer(75), new JLabel("Manager"));
        sliderLable.put(new Integer(100), new JLabel("Admin"));
        userLevel.setLabelTable(sliderLable);
        setDescription();
        btnSave.setVisible(false);
        
    }
    public AddLevel(String level){
        this();
        System.out.println(level);
        initComponents();
        setDescription();
        if (level.equals("guest")) {
            userLevel.setValue(0);
        }else if (level.equals("cashier")) {
            userLevel.setValue(25);
            
        }else if (level.equals("stock handler")) {
            userLevel.setValue(50);
            
        }else if (level.equals("manager")) {
            userLevel.setValue(75);
            
        }else if (level.equals("admin")) {
            userLevel.setValue(100);
            
        }
    }
        String emp = null;
    public AddLevel(String EmpId,String user,String level){
        this();        
        emp=EmpId;
        initComponents();
        setDescription();
        btnBack.setVisible(false);
        btnNext.setVisible(false);
        btnSave.setVisible(true);
        
        if (level.equals("guest")) {
            userLevel.setValue(0);
        }else if (level.equals("cashier")) {
            userLevel.setValue(25);
            
        }else if (level.equals("stock handler")) {
            userLevel.setValue(50);
            
        }else if (level.equals("manager")) {
            userLevel.setValue(75);
            
        }else if (level.equals("admin")) {
            userLevel.setValue(100);
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        lblChangeImage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        userLevel = new javax.swing.JSlider();
        lblContent = new javax.swing.JLabel();
        lblLevelTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblChangeImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChangeImage.setText("Add Security Level");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userLevel.setMajorTickSpacing(25);
        userLevel.setOrientation(javax.swing.JSlider.VERTICAL);
        userLevel.setPaintLabels(true);
        userLevel.setPaintTicks(true);
        userLevel.setSnapToTicks(true);
        userLevel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                userLevelStateChanged(evt);
            }
        });

        lblContent.setText("jLabel2");

        lblLevelTitle.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLevelTitle)
                    .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblLevelTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblContent, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChangeImage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addGap(14, 14, 14)
                        .addComponent(btnCancel)
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChangeImage)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(379, 0, 608, 541);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        int i = userLevel.getValue();
        if (i==0) {
            Home.addUser.put("level", "guest");
        }else if (i==25) {
            Home.addUser.put("level", "cashier");
        }else if (i==50) {
            Home.addUser.put("level", "stock handler");
        }else if (i==75) {
            Home.addUser.put("level", "manager");
        }else if (i==100) {
            Home.addUser.put("level", "admin");
        }
        this.dispose();
        changeProfileImage changeImage = new changeProfileImage();
        Home.jDesktopPane2.add(changeImage);
        changeImage.setVisible(true);
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        int i = JOptionPane.showConfirmDialog(this, "Do you want to cancel?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i==0) {
            this.dispose();
            Home.addUser.clear();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void userLevelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_userLevelStateChanged
        setDescription();
    }

    public void setDescription() {
        int i = userLevel.getValue();
        if (i==0) {
            lblLevelTitle.setText("Guest");
            lblContent.setText("User can only view the specific data and reports only");
        }else if (i==25) {
            lblLevelTitle.setText("Cashier");
            lblContent.setText("User can view stock and handle transactions");
            
        }else if (i==50) {
            lblLevelTitle.setText("Stock Handler");
            lblContent.setText("User can handle the stock");
        }else if (i==75) {
            lblLevelTitle.setText("Manager");
            lblContent.setText("User can handle the specific data");
        }else if (i==100) {
            lblLevelTitle.setText("Administrator");
            lblContent.setText("User have all the access of the system");
        }
    }//GEN-LAST:event_userLevelStateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        AddPassword pass = new AddPassword(Home.addUser.get("Password").toString(), Home.addUser.get("Tip").toString());
        Home.jDesktopPane2.add(pass);
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        int i = userLevel.getValue();
        String level=null;
        if (i==0) {
            level="guest";
        }else if (i==25) {
            level="cashier";
        }else if (i==50) {
            level="stock handler";
        }else if (i==75) {
            level="manager";
        }else if (i==100) {
            level="admin";
        }
        try {
            new JDBC().putData("UPDATE user SET level='"+level+"' WHERE userId='"+emp+"'");
            userManagment mng = new userManagment();
            mng.getUserinfo();
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblChangeImage;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblLevelTitle;
    private javax.swing.JSlider userLevel;
    // End of variables declaration//GEN-END:variables
}
