/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Deeptha Senanayake
 */
public class AddNewItem extends javax.swing.JFrame {

    String item=null;
    /**
     * Creates new form AddNewItem
     */
    NewPro1 newpro1 = new NewPro1();
    NewPro2 newpro2 = new NewPro2();
    boolean[] next = new boolean[4];
    boolean[] back = new boolean[4];
    public AddNewItem() {
        initComponents();
        First();
        next[1]=true;
        
    }
    void First(){
        panel_Window.removeAll();
        panel_Window.add(newpro1);
        newpro1.setSize(443, 367);
        newpro1.setVisible(true);
        panel_Window.repaint();
        btn_next.setText("Next");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cancel = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Window = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_back.setText("Back");
        btn_back.setEnabled(false);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Window.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panel_WindowFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panel_WindowLayout = new javax.swing.GroupLayout(panel_Window);
        panel_Window.setLayout(panel_WindowLayout);
        panel_WindowLayout.setHorizontalGroup(
            panel_WindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_WindowLayout.setVerticalGroup(
            panel_WindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 211, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel_Window))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Window, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_next)
                    .addComponent(btn_cancel)
                    .addComponent(btn_back))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed

        int conf = JOptionPane.showConfirmDialog(this, "<html>Are you sure want to <b>Exit !</html>","Add New Product Wizard",0);
        if (conf==0) {
            dispose();
        }

    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        if (back[0]) {
            First();
            btn_back.setEnabled(false);
            next[1]=true;
        }

    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        
        if (next[1]) {
            
            if (newpro1.isNotEmpty()) {
                boolean yes=false;                
                try {
                    ResultSet r = new JDBC().getData("SELECT item_des FROM items WHERE item_des ='"+newpro1.getDescription()+"' ");
                    if (r.next()) {
                       int cont = JOptionPane.showConfirmDialog(this, "This item is already in your database !\nDo you need to continue ?","Build PC",0);
                        if (cont==0) {
                            yes=true;
                        } else {
                            yes=false;
                        } 
                    }else{
                        yes=true;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                if (yes) {
                    newpro2.setDetails(newpro1.getModel().toUpperCase(),newpro1.getCategory().toUpperCase(),newpro1.getDescription().toUpperCase());
                    panel_Window.removeAll();
                    panel_Window.add(newpro2);
                    newpro2.setSize(443, 367);
                    newpro2.setVisible(true);
                    panel_Window.repaint();

                    btn_back.setEnabled(true);
                    btn_next.setText("Next");

                    back[0]=true;
                    next[1]=false;
                    next[2]=true;  
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Please Fill All Fields !");
            }

        }else if(next[2]){
            NewPro3 newpro3 = new NewPro3();
            String currentID = genItemID();
            try {                
                new JDBC().putData("INSERT INTO items VALUES('"+currentID+"','"+newpro1.getCategory().toUpperCase()+"','"+newpro1.getModel().toUpperCase()+"','"+newpro1.getDescription().toUpperCase()+"') ");
                newpro3.setID(currentID);
                panel_Window.removeAll();
                panel_Window.add(newpro3);
                newpro3.setSize(443, 367);
                newpro3.setVisible(true);
                panel_Window.repaint();

                item = currentID+" "+newpro1.getDescription().toUpperCase();
                btn_back.setEnabled(false);
                btn_cancel.setEnabled(false);
                next[2]=false;
                next[3]=true;
                btn_next.setText("Finish");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error while adding New item");
                e.printStackTrace();
            }

        }else if(next[3]){
            DefaultComboBoxModel model1 = (DefaultComboBoxModel) AddNewStockItems.item_ID.getModel();
            model1.addElement(item);
            AddNewStockItems.item_ID.setSelectedItem(item);
            dispose();
            AddNewStockItems.spin_qty.grabFocus();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        btn_cancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void panel_WindowFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panel_WindowFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_panel_WindowFocusGained

    String genItemID(){
        int num=0;
        try {
            
            ResultSet r = new JDBC().getData("SELECT COUNT(item_id) AS total FROM items");
            if (r.next()) {
                num = r.getInt("total")+1;
            }else{
                num=1;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "S"+String.format("%05d",num);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane panel_Window;
    // End of variables declaration//GEN-END:variables
}
