/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.Format;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thusitha
 */
public class bankAccounts extends javax.swing.JInternalFrame {

    /**
     * Creates new form bankAccounts
     */
    public bankAccounts() {
        super("Bank Accounts", false, true, false, true);
        initComponents();
        validation();
        setBankAccount(); 
        btnPrint.setVisible(false);
    }
    NumberFormat f = NumberFormat.getInstance();
    static double overDraft=50000;
    String date;
    public void validation(){
        txtBankName.setEnabled(false);
        txtAccName.setEnabled(false);
        txtBankBranch.setEnabled(false);
        txtOpenedBalance.setEnabled(false);
        txtTelephone.setEnabled(false);
        cmboAccType.setEnabled(false);
        txtDate.setEnabled(false);
        btnClear.setEnabled(false);
        btnPrint.setEnabled(false);
        btnSave.setEnabled(false);
        txtInterest.setEnabled(false);
        txtAccNo.setEnabled(true);
        
    }
    public void clear(){        
        txtBankName.setText("");
        txtAccName.setText("");
        txtBankBranch.setText("");
        txtOpenedBalance.setText("");
        txtTelephone.setText("");
        cmboAccType.setSelectedIndex(0);
        txtInterest.setText("");
        txtAccNo.setText("");
    }
    
    public void setBankAccount(){
        DefaultTableModel dtm = (DefaultTableModel) tblAccounts.getModel();
        
        int a = dtm.getRowCount();
        for (int i = 0; i < a; i++) {
            dtm.removeRow(0);
        }
        
        try {
            ResultSet r = new JDBC().getData("SELECT * FROM bankAccount");
            while(r.next()){
                
//                String s = String.valueOf(Double.parseDouble(r.getString("interest"))*100)+"%";
                String s = f.format(Double.parseDouble(r.getString("interest"))*100)+"%";
                Vector v = new Vector();
                v.add(r.getString("accNo"));
                v.add(r.getString("bankName"));
                v.add(r.getString("accName"));
                v.add(r.getString("type"));
                v.add(r.getString("openedDate"));
                v.add(r.getString("branch"));
                v.add(r.getString("tel"));
                v.add(r.getString("balance"));
                v.add(s);
                
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtAccName = new javax.swing.JTextField();
        cmboAccType = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBankBranch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        txtTelephone = new javax.swing.JFormattedTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtOpenedBalance = new javax.swing.JFormattedTextField();
        btnPrint = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtInterest = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Bank Accounts");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 51, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/moneybox-64.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 31, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/check_book-64.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Account No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Bank Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Acount Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Interest");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtAccNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccNoKeyPressed(evt);
            }
        });
        jPanel1.add(txtAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 112, 269, -1));

        txtBankName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBankName.setEnabled(false);
        txtBankName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBankNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 153, 269, -1));

        txtAccName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccName.setEnabled(false);
        txtAccName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAccNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtAccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 194, 269, -1));

        cmboAccType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmboAccType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---", "Savings", "Current", "Fixed" }));
        cmboAccType.setEnabled(false);
        cmboAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboAccTypeActionPerformed(evt);
            }
        });
        cmboAccType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmboAccTypeKeyPressed(evt);
            }
        });
        jPanel1.add(cmboAccType, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 235, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Opened Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 115, -1, -1));

        lblBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBalance.setText("Balance                          Rs.");
        jPanel1.add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 156, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Bank Branch");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 197, -1, -1));

        txtBankBranch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBankBranch.setEnabled(false);
        txtBankBranch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBankBranchKeyPressed(evt);
            }
        });
        jPanel1.add(txtBankBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 194, 339, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Telephone No");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 238, -1, -1));

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No", "Bank Name", "Account Name", "Account Type", "Opened Date", "Bank Branch", "Telephone", "Current Balance", "Interest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccounts.setOpaque(false);
        tblAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccounts);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 361, 1350, 330));

        try {
            txtTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-# ### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelephone.setEnabled(false);
        txtTelephone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelephoneKeyPressed(evt);
            }
        });
        jPanel1.add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 235, 340, -1));

        txtDate.setDateFormatString("yyyy-MM-dd");
        txtDate.setEnabled(false);
        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
        });
        txtDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDatePropertyChange(evt);
            }
        });
        txtDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateKeyPressed(evt);
            }
        });
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 112, 220, 25));

        txtOpenedBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtOpenedBalance.setEnabled(false);
        txtOpenedBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOpenedBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOpenedBalanceKeyPressed(evt);
            }
        });
        jPanel1.add(txtOpenedBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 153, 340, -1));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/printer-32.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, 110, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/save-32.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, 110, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/rename-32.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 310, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Acount Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 238, -1, -1));

        txtInterest.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        txtInterest.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtInterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInterestKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInterestKeyTyped(evt);
            }
        });
        jPanel1.add(txtInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 276, 90, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        saveRecords();
        

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtAccNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccNoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtAccNo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Account Number");
                txtAccNo.grabFocus();
            }else{
                try {
                    ResultSet r = new JDBC().getData("SELECT * FROM bankaccount WHERE accNo='"+txtAccNo.getText()+"'");
                    if (r.first()) {
                        JOptionPane.showMessageDialog(this, "Record has found.");
                    }else{
                        txtBankName.grabFocus();
                        txtBankName.setEnabled(true);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_txtAccNoKeyPressed

    private void txtBankNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankNameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtBankName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Bank Name");
                txtBankName.grabFocus();
            }else{
                txtAccName.setEnabled(true);
                txtAccName.grabFocus();
            }
        }
    }//GEN-LAST:event_txtBankNameKeyPressed

    private void txtAccNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccNameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtAccName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter account name");
                txtAccName.grabFocus();
            }else{
                cmboAccType.setEnabled(true);
                cmboAccType.grabFocus();
            }
        }
    }//GEN-LAST:event_txtAccNameKeyPressed

    private void txtDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDatePropertyChange

        
        
    }//GEN-LAST:event_txtDatePropertyChange

    private void txtDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtDateAncestorAdded
        
    }//GEN-LAST:event_txtDateAncestorAdded

    private void cmboAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboAccTypeActionPerformed

        if (cmboAccType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a account type");
            cmboAccType.grabFocus();
        }else{
            if (cmboAccType.getSelectedItem().equals("Current")) {
                txtInterest.setText("0.00");
                txtInterest.setEnabled(false);
                txtDate.setEnabled(true);
                txtDate.grabFocus();                
            }else{
                txtInterest.setEnabled(true);
                txtInterest.grabFocus();
            }
        }
        
    }//GEN-LAST:event_cmboAccTypeActionPerformed

    private void cmboAccTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmboAccTypeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_0) {
            cmboAccType.setSelectedIndex(0);
        }else if (evt.getKeyCode() == KeyEvent.VK_1) {
            cmboAccType.setSelectedIndex(1);
        }else if (evt.getKeyCode() == KeyEvent.VK_2) {
            cmboAccType.setSelectedIndex(2);
        }else if (evt.getKeyCode() == KeyEvent.VK_3) {
            cmboAccType.setSelectedIndex(3);
        }
    }//GEN-LAST:event_cmboAccTypeKeyPressed

    private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtOpenedBalance.setEnabled(true);
            txtOpenedBalance.grabFocus();
            
        }
    }//GEN-LAST:event_txtDateKeyPressed

    private void txtOpenedBalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpenedBalanceKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtOpenedBalance.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the bank balance");
                txtOpenedBalance.grabFocus();
            }else{
                txtBankBranch.setEnabled(true);
                txtTelephone.setEnabled(true);
                btnClear.setEnabled(true);
                btnPrint.setEnabled(true);
                btnSave.setEnabled(true);
                txtBankBranch.grabFocus();
            }
        }
    }//GEN-LAST:event_txtOpenedBalanceKeyPressed

    private void txtTelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtTelephone.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the bank telephone number");
            }else{
                btnSave.grabFocus();
            }
        }
    }//GEN-LAST:event_txtTelephoneKeyPressed

    private void txtBankBranchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankBranchKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtBankBranch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the bank branch name");
            }else{
                txtTelephone.grabFocus();
            }
        }
    }//GEN-LAST:event_txtBankBranchKeyPressed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            saveRecords();
        }
    }//GEN-LAST:event_btnSaveKeyPressed

    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained

        txtOpenedBalance.setEnabled(true);
    }//GEN-LAST:event_txtDateFocusGained

    private void tblAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountsMouseClicked

        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            int i = JOptionPane.showConfirmDialog(this, "Do you want to edit this record?", "Caution", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (i==0) {
                
                int j = tblAccounts.getSelectedRow();
                txtAccNo.setText((String) tblAccounts.getValueAt(j, 0));
                txtBankName.setText(String.valueOf(tblAccounts.getValueAt(j, 1)));
                txtAccName.setText(String.valueOf(tblAccounts.getValueAt(j, 2)));
                cmboAccType.setSelectedItem(String.valueOf(tblAccounts.getValueAt(j, 3)));
                String da = String.valueOf(tblAccounts.getValueAt(j, 4));
                try {
                    Date d = new SimpleDateFormat("yyyy-MM-dd").parse(da);
                    txtDate.setDate(d);
                    
                } catch (ParseException ex) {
                    Logger.getLogger(bankAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                txtBankBranch.setText(String.valueOf(tblAccounts.getValueAt(j, 5)));
                txtTelephone.setText(String.valueOf(tblAccounts.getValueAt(j, 6)));
                Double number = new Double((String) tblAccounts.getValueAt(j, 7));
                NumberFormat n = NumberFormat.getNumberInstance();
                txtOpenedBalance.setText(n.format(number));
                txtInterest.setText(String.valueOf(tblAccounts.getValueAt(j, 8)));
                
                txtAccNo.setEnabled(false);
                txtBankName.setEnabled(true);
                txtAccName.setEnabled(true);
                cmboAccType.setEnabled(true);
                txtDate.setEnabled(true);
                txtBankBranch.setEnabled(true);
                txtTelephone.setEnabled(true);
                txtOpenedBalance.setEnabled(false);
                txtInterest.setEnabled(true);
                txtOpenedBalance.setEnabled(true);
                
//                btnSave.setEnabled(true);
//                btnClear.setEnabled(true);
//                btnPrint.setEnabled(true);
            }else if (i==1) {
                clear();
            }
        }
    }//GEN-LAST:event_tblAccountsMouseClicked

    private void txtInterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInterestKeyTyped

        
    }//GEN-LAST:event_txtInterestKeyTyped

    private void txtInterestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInterestKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtInterest.setText(txtInterest.getText()+"%");
            txtDate.setEnabled(true);
            txtDate.grabFocus();
        }
    }//GEN-LAST:event_txtInterestKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmboAccType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JTextField txtAccName;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtBankBranch;
    private javax.swing.JTextField txtBankName;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JFormattedTextField txtInterest;
    private javax.swing.JFormattedTextField txtOpenedBalance;
    private javax.swing.JFormattedTextField txtTelephone;
    // End of variables declaration//GEN-END:variables

    
    void saveRecords() throws HeadlessException {
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        date = sd.format(txtDate.getDate()); 
        
        int count = tblAccounts.getRowCount();
        String s = "";
        for (int i = 0; i < count; i++) {
            String column = (String) tblAccounts.getValueAt(i, 0);
            if (column.equals(txtAccNo.getText())) {
                s="true";
                break;
            }else{
                s="false";
            }
        }
        if (s.equals("true")) {
            String balance = String.valueOf(txtOpenedBalance.getValue());
            System.out.println(balance);
            try {
                new JDBC().putData("UPDATE bankAccount SET bankName='"+txtBankName.getText()+"', accName='"+txtAccName.getText()+"', type='"+cmboAccType.getSelectedItem()+"', Balance='"+balance+"', branch='"+txtBankBranch.getText()+"', tel='"+txtTelephone.getValue()+"', interest='"+txtInterest.getValue()+"' WHERE accNo='"+txtAccNo.getText()+"'");
                JOptionPane.showMessageDialog(this, "Record has been saved.");
                setBankAccount();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            clear();
            validation();
            txtAccNo.setText("");
            txtAccNo.grabFocus();            
        }else if(s.equals("false")){       
        
            if (txtAccNo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the Account Number");
                txtAccNo.grabFocus();                
            }else if (txtOpenedBalance.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the bank balance");                
            }else{
                try {
                    new JDBC().putData("INSERT INTO bankAccount VALUES('"+txtAccNo.getText()+"','"+txtBankName.getText()+"','"+txtAccName.getText()+"','"+cmboAccType.getSelectedItem()+"','"+date+"','"+txtOpenedBalance.getValue()+"','"+txtBankBranch.getText()+"','"+txtTelephone.getValue()+"','"+txtInterest.getValue()+"')");
                    JOptionPane.showMessageDialog(this, "Record has been saved.");
                    setBankAccount();
                } catch (Exception ex) {
                    Logger.getLogger(bankAccounts.class.getName()).log(Level.SEVERE, null, ex);
                }
                clear();
                validation();
                txtAccNo.setText("");
                txtAccNo.grabFocus();
            }
            
        }
    }
}
