/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Thusitha
 */
public class BuildPCHome extends javax.swing.JFrame {

    /**
     * Creates new form BuildPCHome
     */
    public BuildPCHome() {
        initComponents();
        
        
        pnlMenu.setVisible(false);
        jDesktopPane1.setVisible(false);
        pnlPower.setVisible(false);
        pnlDesktop.setVisible(true);
        pnlCustMenu.setVisible(false);
//        pnlDesktop.setVisible(false);
        setExtendedState(MAXIMIZED_BOTH);
        
//        pnlDesktopMainBack.setBackground(new Color(0, 0, 0, 80));
//        pnlDeskIconBack.setBackground(new Color(0, 0, 0, 20));
        
        dropDownSearchList();
        setTime();
        System.out.println(userLevel);
    }
    static String userLevel = "admin";
    
    void setTime(){
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                String time = df.format(d);
                lblClock.setText(time);
            }
        }).start();
    }
    
    void dropDownSearchList(){
        Vector v = new Vector();
        ImageIcon cust = new ImageIcon(getClass().getResource("/images/customer_1.png"));
        ImageIcon emp = new ImageIcon(getClass().getResource("/images/employee.png"));
        ImageIcon Invoice = new ImageIcon(getClass().getResource("/images/invoice.png"));
        ImageIcon supp = new ImageIcon(getClass().getResource("/images/supplier.png"));
        ImageIcon stock = new ImageIcon(getClass().getResource("/images/stock.png"));
        
        v.add(cust);
        v.add(emp);
        v.add(Invoice);
        v.add(supp);
        v.add(stock);
        jComboBox1.setModel(new DefaultComboBoxModel(v));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotifi = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblPower = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblsearch = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lblStart = new javax.swing.JLabel();
        lblTaskBar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMenuOp1 = new javax.swing.JLabel();
        lblMenuOp2 = new javax.swing.JLabel();
        lblMenuOp3 = new javax.swing.JLabel();
        lblMenuOp4 = new javax.swing.JLabel();
        lblMenuOp5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMenuFinance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        lblMenuFinance2 = new javax.swing.JLabel();
        lblMenuFinance1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblMenuFinance3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlPower = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblShowDesk = new javax.swing.JLabel();
        lblLogOff = new javax.swing.JLabel();
        lblLock = new javax.swing.JLabel();
        lblShutDown = new javax.swing.JLabel();
        pnlDesktop = new javax.swing.JPanel();
        pnlCustMenu1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlCustMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFinanceDesk = new javax.swing.JLabel();
        lblCustomerDesk = new javax.swing.JLabel();
        lblInvoiceDesk = new javax.swing.JLabel();
        lblStockDesk = new javax.swing.JLabel();
        lblSupplierDesk = new javax.swing.JLabel();
        lblEmployeeDesk = new javax.swing.JLabel();
        lblReportDesk = new javax.swing.JLabel();
        lblDesktop = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNotifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        lblNotifi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNotifiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNotifiMouseExited(evt);
            }
        });
        getContentPane().add(lblNotifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, 30));

        lblClock.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 190, 30));

        lblPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/powerSelected.png"))); // NOI18N
        lblPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPowerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPowerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPowerMouseExited(evt);
            }
        });
        getContentPane().add(lblPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        txtSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(null);
        txtSearch.setOpaque(false);
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchMouseExited(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 170, 30));

        lblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text.png"))); // NOI18N
        getContentPane().add(lblsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 50, 30));

        lblStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.png"))); // NOI18N
        lblStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStartMouseExited(evt);
            }
        });
        getContentPane().add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblTaskBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taskBar.png"))); // NOI18N
        lblTaskBar.setText("jLabel1");
        getContentPane().add(lblTaskBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(0, 51, 255));
        pnlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMenuMouseExited(evt);
            }
        });
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 10, 120));

        lblMenuOp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMenuOp1.setText("jLabel7");
        lblMenuOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuOp1MouseClicked(evt);
            }
        });
        pnlMenu.add(lblMenuOp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblMenuOp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMenuOp2.setText("jLabel7");
        lblMenuOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuOp2MouseClicked(evt);
            }
        });
        pnlMenu.add(lblMenuOp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        lblMenuOp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMenuOp3.setText("jLabel8");
        lblMenuOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuOp3MouseClicked(evt);
            }
        });
        pnlMenu.add(lblMenuOp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        lblMenuOp4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMenuOp4.setText("jLabel9");
        lblMenuOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuOp4MouseClicked(evt);
            }
        });
        pnlMenu.add(lblMenuOp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        lblMenuOp5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMenuOp5.setText("jLabel10");
        lblMenuOp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuOp5MouseClicked(evt);
            }
        });
        pnlMenu.add(lblMenuOp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Finance");
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer");
        pnlMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        lblMenuFinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/financeMain.png"))); // NOI18N
        lblMenuFinance.setText("jLabel4");
        lblMenuFinance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuFinanceMouseEntered(evt);
            }
        });
        pnlMenu.add(lblMenuFinance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 130, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customerMain.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        pnlMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 120));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 10, 120));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlMenu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 10, 120));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlMenu.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 10, 120));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlMenu.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 10, 120));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlMenu.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 10, 120));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/employeeMain.png"))); // NOI18N
        jLabel20.setText("jLabel6");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });
        pnlMenu.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 130, 120));

        lblMenuFinance2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/supplierMain.png"))); // NOI18N
        lblMenuFinance2.setText("jLabel4");
        lblMenuFinance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuFinance2MouseEntered(evt);
            }
        });
        pnlMenu.add(lblMenuFinance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 130, 120));

        lblMenuFinance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/stockMain.png"))); // NOI18N
        lblMenuFinance1.setText("jLabel4");
        lblMenuFinance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuFinance1MouseEntered(evt);
            }
        });
        pnlMenu.add(lblMenuFinance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 130, 120));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/invoiceMain.png"))); // NOI18N
        jLabel18.setText("jLabel6");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });
        pnlMenu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 120));

        lblMenuFinance3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/reportMain.png"))); // NOI18N
        lblMenuFinance3.setText("jLabel4");
        lblMenuFinance3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuFinance3MouseEntered(evt);
            }
        });
        pnlMenu.add(lblMenuFinance3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 130, 120));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Report");
        pnlMenu.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Employee");
        pnlMenu.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Supplier");
        pnlMenu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Stock");
        pnlMenu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Invoice");
        pnlMenu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuBack.png"))); // NOI18N
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 190));

        jPanel1.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 190));

        pnlPower.setBackground(new java.awt.Color(102, 102, 102));
        pnlPower.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlPower.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 260));

        lblShowDesk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblShowDesk.setForeground(new java.awt.Color(255, 255, 255));
        lblShowDesk.setText("Show Desktop");
        lblShowDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShowDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowDeskMouseClicked(evt);
            }
        });
        pnlPower.add(lblShowDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        lblLogOff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLogOff.setForeground(new java.awt.Color(255, 255, 255));
        lblLogOff.setText("Log Off");
        lblLogOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPower.add(lblLogOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblLock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLock.setForeground(new java.awt.Color(255, 255, 255));
        lblLock.setText("Lock the System");
        lblLock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLockMouseClicked(evt);
            }
        });
        pnlPower.add(lblLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblShutDown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblShutDown.setForeground(new java.awt.Color(255, 255, 255));
        lblShutDown.setText("Shut Down");
        lblShutDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShutDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShutDownMouseClicked(evt);
            }
        });
        pnlPower.add(lblShutDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel1.add(pnlPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 140, -1));

        pnlDesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCustMenu1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("jLabel4");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel7");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel8");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel9");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jLabel10");

        javax.swing.GroupLayout pnlCustMenu1Layout = new javax.swing.GroupLayout(pnlCustMenu1);
        pnlCustMenu1.setLayout(pnlCustMenu1Layout);
        pnlCustMenu1Layout.setHorizontalGroup(
            pnlCustMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlCustMenu1Layout.setVerticalGroup(
            pnlCustMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pnlDesktop.add(pnlCustMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        pnlCustMenu.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel9");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout pnlCustMenuLayout = new javax.swing.GroupLayout(pnlCustMenu);
        pnlCustMenu.setLayout(pnlCustMenuLayout);
        pnlCustMenuLayout.setHorizontalGroup(
            pnlCustMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlCustMenuLayout.setVerticalGroup(
            pnlCustMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pnlDesktop.add(pnlCustMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 170, 220));

        lblFinanceDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/financeDesktop.png"))); // NOI18N
        lblFinanceDesk.setToolTipText("Finance");
        lblFinanceDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFinanceDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinanceDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFinanceDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFinanceDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblFinanceDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 600, -1, -1));

        lblCustomerDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/customerDesktop.png"))); // NOI18N
        lblCustomerDesk.setToolTipText("Customer");
        lblCustomerDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomerDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomerDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblCustomerDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 600, -1, -1));

        lblInvoiceDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/invoiceDesktop.png"))); // NOI18N
        lblInvoiceDesk.setToolTipText("Invoice");
        lblInvoiceDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInvoiceDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvoiceDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInvoiceDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInvoiceDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblInvoiceDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 600, -1, -1));

        lblStockDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/stockDesktop.png"))); // NOI18N
        lblStockDesk.setToolTipText("Stock");
        lblStockDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStockDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStockDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStockDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStockDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblStockDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 70, 70));

        lblSupplierDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/supplierDesktop.png"))); // NOI18N
        lblSupplierDesk.setToolTipText("Supplier");
        lblSupplierDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSupplierDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblSupplierDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 600, -1, -1));

        lblEmployeeDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/employeeDesktop.png"))); // NOI18N
        lblEmployeeDesk.setToolTipText("Employee");
        lblEmployeeDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEmployeeDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmployeeDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmployeeDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblEmployeeDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 600, -1, -1));

        lblReportDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/reportDesktop.png"))); // NOI18N
        lblReportDesk.setToolTipText("Reports");
        lblReportDesk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReportDesk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportDeskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportDeskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportDeskMouseExited(evt);
            }
        });
        pnlDesktop.add(lblReportDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 600, -1, -1));

        lblDesktop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop.png"))); // NOI18N
        lblDesktop.setText("jLabel10");
        pnlDesktop.add(lblDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        jPanel1.add(pnlDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, 730));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNotifiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNotifiMouseClicked

    private void lblNotifiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifiMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/notificationSelect.png"));
        lblNotifi.setIcon(ii);
    }//GEN-LAST:event_lblNotifiMouseEntered

    private void lblNotifiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifiMouseExited

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/notification.png"));
        lblNotifi.setIcon(ii);
    }//GEN-LAST:event_lblNotifiMouseExited

     int powerMenuCount=0;
    private void lblPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerMouseClicked
        // TODO add your handling code here:
        pnlPower.setVisible(true);
        new Thread(new Runnable() {

            @Override
            public void run() {
                if (powerMenuCount==0) {
                    for (int i = 0; i < 260; i++) {
                        try {
                            pnlPower.setSize(140, i);
                            Thread.sleep(3);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        powerMenuCount =1;
                    }
                }else if(powerMenuCount==1){
                    for (int i = 260; i > 0; i--) {
                        try {
                            pnlPower.setSize(140, i);
                            Thread.sleep(3);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        powerMenuCount=0;
                    }
                pnlPower.setVisible(false);
                    
                }
            }
        }).start();
    }//GEN-LAST:event_lblPowerMouseClicked

    private void lblPowerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/power.png"));
        lblPower.setIcon(ii);
    }//GEN-LAST:event_lblPowerMouseEntered

    private void lblPowerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerMouseExited

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/powerSelected.png"));
        lblPower.setIcon(ii);
    }//GEN-LAST:event_lblPowerMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.setVisible(true);
        FinanceSupPayment supPay = new FinanceSupPayment();
        jDesktopPane1.add(supPay);
        supPay.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/textSelected.png"));
        lblsearch.setIcon(ii);
    }//GEN-LAST:event_txtSearchMouseEntered

    private void txtSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseExited

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/text.png"));
        lblsearch.setIcon(ii);
    }//GEN-LAST:event_txtSearchMouseExited

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/textSelected.png"));
        lblsearch.setIcon(ii);
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained

    }//GEN-LAST:event_txtSearchFocusGained

    private void lblStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseClicked

        menuDropDown();
    }//GEN-LAST:event_lblStartMouseClicked

    private void lblStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/startSelected.png"));
        lblStart.setIcon(ii);
    }//GEN-LAST:event_lblStartMouseEntered

    private void lblStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseExited

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/start.png"));
        lblStart.setIcon(ii);
    }//GEN-LAST:event_lblStartMouseExited

    private void lblReportDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportDeskMouseExited

        lblReportDesk.setLocation(951, 600);
    }//GEN-LAST:event_lblReportDeskMouseExited

    private void lblReportDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportDeskMouseEntered

        lblReportDesk.setLocation(951, 590);
    }//GEN-LAST:event_lblReportDeskMouseEntered

    private void lblReportDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportDeskMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblReportDeskMouseClicked

    private void lblEmployeeDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeDeskMouseExited

        lblEmployeeDesk.setLocation(851, 600);
    }//GEN-LAST:event_lblEmployeeDeskMouseExited

    private void lblEmployeeDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeDeskMouseEntered

        lblEmployeeDesk.setLocation(851, 590);
    }//GEN-LAST:event_lblEmployeeDeskMouseEntered

    private void lblEmployeeDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeDeskMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblEmployeeDeskMouseClicked

    private void lblSupplierDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierDeskMouseExited

        lblSupplierDesk.setLocation(751, 600);
    }//GEN-LAST:event_lblSupplierDeskMouseExited

    private void lblSupplierDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierDeskMouseEntered

        lblSupplierDesk.setLocation(751, 590);
    }//GEN-LAST:event_lblSupplierDeskMouseEntered

    private void lblSupplierDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierDeskMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblSupplierDeskMouseClicked

    private void lblStockDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockDeskMouseExited

        lblStockDesk.setLocation(651, 600);
    }//GEN-LAST:event_lblStockDeskMouseExited

    private void lblStockDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockDeskMouseEntered

        lblStockDesk.setLocation(651, 590);
    }//GEN-LAST:event_lblStockDeskMouseEntered

    private void lblStockDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockDeskMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblStockDeskMouseClicked

    private void lblInvoiceDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceDeskMouseExited

        lblInvoiceDesk.setLocation(551, 600);
    }//GEN-LAST:event_lblInvoiceDeskMouseExited

    private void lblInvoiceDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceDeskMouseEntered

        lblInvoiceDesk.setLocation(551, 590);
    }//GEN-LAST:event_lblInvoiceDeskMouseEntered

    private void lblInvoiceDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceDeskMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblInvoiceDeskMouseClicked

    private void lblCustomerDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerDeskMouseExited

        lblCustomerDesk.setLocation(351, 600);
    }//GEN-LAST:event_lblCustomerDeskMouseExited

    private void lblCustomerDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerDeskMouseEntered
        // TODO add your handling code here:
        lblCustomerDesk.setLocation(351, 590);
    }//GEN-LAST:event_lblCustomerDeskMouseEntered

    private void lblCustomerDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerDeskMouseClicked
        pnlCustMenu.setLocation(310, 600);
        iconMenuX = 310;
        panel = pnlCustMenu;

        if (custMenuCount ==0) {
            iconMenuOpen();
            custMenuCount = 1;
        }else if(custMenuCount == 1){
            iconMenuClose();
            custMenuCount = 0;
        }
    }//GEN-LAST:event_lblCustomerDeskMouseClicked

    private void lblFinanceDeskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinanceDeskMouseExited

        lblFinanceDesk.setLocation(451, 600);
    }//GEN-LAST:event_lblFinanceDeskMouseExited

    private void lblFinanceDeskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinanceDeskMouseEntered

        lblFinanceDesk.setLocation(451, 590);
    }//GEN-LAST:event_lblFinanceDeskMouseEntered

    private void lblFinanceDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinanceDeskMouseClicked

    }//GEN-LAST:event_lblFinanceDeskMouseClicked

    private void lblShutDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShutDownMouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_lblShutDownMouseClicked

    private void lblLockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLockMouseClicked
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_lblLockMouseClicked

    private void lblShowDeskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowDeskMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.setVisible(false);
        pnlDesktop.setVisible(true);
    }//GEN-LAST:event_lblShowDeskMouseClicked

    private void pnlMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuMouseExited
        //        menuDropDown();
    }//GEN-LAST:event_pnlMenuMouseExited

    private void lblMenuFinance3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuFinance3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuFinance3MouseEntered

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void lblMenuFinance1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuFinance1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuFinance1MouseEntered

    private void lblMenuFinance2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuFinance2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuFinance2MouseEntered

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void lblMenuFinanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuFinanceMouseEntered

        lblMenuOp1.setText("Supplier Payment");
        lblMenuOp2.setText("Bank Accounts");
        lblMenuOp3.setText("Cache Book");
        lblMenuOp4.setText("Cheque Book");
        lblMenuOp5.setText("Cheque Transaction");
    }//GEN-LAST:event_lblMenuFinanceMouseEntered

    private void lblMenuOp5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuOp5MouseClicked

        menuDropDown();
        jDesktopPane1.setVisible(true);
        if (lblMenuOp5.getText().equals("Cheque Transaction")) {
            chequeTransaction chacheTrance = new chequeTransaction();
            jDesktopPane1.add(chacheTrance);
            chacheTrance.setVisible(true);

        } else {
        }
    }//GEN-LAST:event_lblMenuOp5MouseClicked

    private void lblMenuOp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuOp4MouseClicked

        menuDropDown();
        jDesktopPane1.setVisible(true);
        if (lblMenuOp4.getText().equals("Cheque Book")) {
            CashBook chache = new CashBook();
            jDesktopPane1.add(chache);
            chache.setVisible(true);

        } else {
        }
    }//GEN-LAST:event_lblMenuOp4MouseClicked

    private void lblMenuOp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuOp3MouseClicked

        menuDropDown();
        jDesktopPane1.setVisible(true);
        if (lblMenuOp3.getText().equals("Cache Book")) {
            chequeBook Cachebook = new chequeBook();
            jDesktopPane1.add(Cachebook);
            Cachebook.setVisible(true);

        } else {
        }
    }//GEN-LAST:event_lblMenuOp3MouseClicked

    private void lblMenuOp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuOp2MouseClicked

        menuDropDown();
        jDesktopPane1.setVisible(true);
        if (lblMenuOp2.getText().equals("Bank Accounts")) {
            bankAccounts banckAccount = new bankAccounts();
            jDesktopPane1.add(banckAccount);
            banckAccount.setVisible(true);

        } else {
        }
    }//GEN-LAST:event_lblMenuOp2MouseClicked

    private void lblMenuOp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuOp1MouseClicked
        jDesktopPane1.repaint();
        menuDropDown();
        pnlDesktop.setVisible(false);
        jDesktopPane1.setVisible(true);
        if (lblMenuOp1.getText().equals("Supplier Payment")) {
            FinanceSupPayment finance = new FinanceSupPayment();
            jDesktopPane1.add(finance);
            finance.setVisible(true);

        } else {
        }
    }//GEN-LAST:event_lblMenuOp1MouseClicked

    int iconMenuX;
    JPanel panel;
    byte custMenuCount=0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildPCHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildPCHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildPCHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildPCHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildPCHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCustomerDesk;
    private javax.swing.JLabel lblDesktop;
    private javax.swing.JLabel lblEmployeeDesk;
    private javax.swing.JLabel lblFinanceDesk;
    private javax.swing.JLabel lblInvoiceDesk;
    private javax.swing.JLabel lblLock;
    private javax.swing.JLabel lblLogOff;
    private javax.swing.JLabel lblMenuFinance;
    private javax.swing.JLabel lblMenuFinance1;
    private javax.swing.JLabel lblMenuFinance2;
    private javax.swing.JLabel lblMenuFinance3;
    private javax.swing.JLabel lblMenuOp1;
    private javax.swing.JLabel lblMenuOp2;
    private javax.swing.JLabel lblMenuOp3;
    private javax.swing.JLabel lblMenuOp4;
    private javax.swing.JLabel lblMenuOp5;
    private javax.swing.JLabel lblNotifi;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblReportDesk;
    private javax.swing.JLabel lblShowDesk;
    private javax.swing.JLabel lblShutDown;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStockDesk;
    private javax.swing.JLabel lblSupplierDesk;
    private javax.swing.JLabel lblTaskBar;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JPanel pnlCustMenu;
    private javax.swing.JPanel pnlCustMenu1;
    private javax.swing.JPanel pnlDesktop;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPower;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
   byte count=0;
    void menuDropDown() {
        //        JMenuItem m1 = new JMenu("new");
        //        jPopupMenu1.add(m1);
        //        jPopupMenu1.show(jLabel1, 0, 0);
                
                new Thread(new Runnable() {

                    @Override
                    public void run() {
                        if (count==0) {
                            pnlMenu.setVisible(true);lblMenuOp1.setText("");
                            lblMenuOp2.setText("");
                            lblMenuOp3.setText("");
                            lblMenuOp4.setText("");
                            lblMenuOp5.setText("");
                            for (int i = 0; i < 190; i++) {
                                try {
                                    pnlMenu.setSize(1366, i);
                                    Thread.sleep(1);
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }
                            count =1;
                        } else if(count==1) {
                            pnlMenu.setVisible(true);
                            for (int i = 190; i > 0; i--) {
                                pnlMenu.setSize(1366, i);
                                try {
                                    Thread.sleep(1);
                                } catch (InterruptedException ex) {
                                    ex.printStackTrace();
                                }                        
                            }
                            count = 0;
                            pnlMenu.setVisible(false);
                        }
                        Thread.currentThread().stop();
                    }
                }).start();
                
    }

    void iconMenuOpen() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                for (int i = 600; i > 370; i--) {
                    panel.setLocation(iconMenuX, i);
                    
                    if (i==400) {
                        panel.setVisible(true);
                    }
                    try {
                        Thread.sleep(1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                Thread.currentThread().stop();
            }
        }).start();
    }
    
    void iconMenuClose(){
        new Thread(new Runnable() {

            @Override
            public void run() {
                for (int i = 370; i < 600; i++) {
                    panel.setLocation(iconMenuX, i);
                    
                    if (i==400) {
                        panel.setVisible(false);
                    }
                    try {
                        Thread.sleep(1);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                Thread.currentThread().stop();
            }
        }).start();
    }
}

