/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.TimingUtils;

/**
 *
 * @author Thusitha
 */
public class changePassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form changePassword
     */
    String pass = Home.password;
    Configs con = new Configs();

    public changePassword() {
        initComponents();
        lblUserName.setText(Home.userName);
        lblUserLevel.setText(Home.level);
        btnChangePass.setEnabled(false);
        passNewPass.setEnabled(false);
        setImage();
    }

    BufferedImage image = null;

    public void setImage() {
        try {
            image = ImageIO.read(new File(con.getProp(Home.userName)));
            ImageIcon ii = new ImageIcon(ScaledImage(image, 124, 140));
            jLabel2.setIcon(ii);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Image ScaledImage(Image img, int w, int h) {

        BufferedImage resizedImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedImage;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserLevel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passCurrent = new javax.swing.JPasswordField();
        passNewPass = new javax.swing.JPasswordField();
        passConfirmPass = new javax.swing.JPasswordField();
        txtPassTip = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Change Your Password");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login/admin.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserName.setText("Username");

        lblUserLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUserLevel.setText("Userlevel");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Current Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("New Password");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Confirm New Password");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Password Tip");

        passCurrent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passCurrent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passCurrentKeyPressed(evt);
            }
        });

        passNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passNewPassKeyPressed(evt);
            }
        });

        passConfirmPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passConfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passConfirmPassKeyPressed(evt);
            }
        });

        txtPassTip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnChangePass.setText("Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName)
                                    .addComponent(lblUserLevel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassTip, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(passCurrent)
                                    .addComponent(passNewPass)
                                    .addComponent(passConfirmPass))))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnChangePass)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserLevel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnChangePass))
                .addContainerGap())
        );

        setBounds(432, 0, 502, 584);
    }// </editor-fold>//GEN-END:initComponents

    RoundedBalloonStyle style = new RoundedBalloonStyle(10, 7, Color.yellow, Color.yellow);
    private void passCurrentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passCurrentKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (String.valueOf(passCurrent.getPassword()).equals(pass)) {
                passNewPass.grabFocus();
                passNewPass.setEnabled(true);
                passConfirmPass.setEnabled(true);

            } else {
                passNewPass.setEnabled(false);
                passConfirmPass.setEnabled(false);
                BalloonTip tip = new BalloonTip(passCurrent, "Your current password does not match.", style, false);
                tip.setVisible(true);
                TimingUtils.showTimedBalloon(tip, 3000);
                passCurrent.setText("");
                passCurrent.grabFocus();

            }
        }
    }//GEN-LAST:event_passCurrentKeyPressed

    private void passNewPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passNewPassKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (String.valueOf(passNewPass.getPassword()).length() > 6) {
                passConfirmPass.grabFocus();
                passConfirmPass.setEnabled(true);

            } else {
                passConfirmPass.setEnabled(false);
                BalloonTip tip = new BalloonTip(passNewPass, "Please enter more than 6 characters.", style, false);
                tip.setVisible(true);
                TimingUtils.showTimedBalloon(tip, 3000);
                passNewPass.grabFocus();

            }
        }
    }//GEN-LAST:event_passNewPassKeyPressed

    private void passConfirmPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passConfirmPassKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (String.valueOf(passConfirmPass.getPassword()).equals(String.valueOf(passConfirmPass.getPassword()))) {
                btnChangePass.setEnabled(true);

            } else {
                passConfirmPass.setEnabled(false);
                BalloonTip tip = new BalloonTip(passNewPass, "Confirm password not matched. Plese enter correct Password.", style, false);
                tip.setVisible(true);
                TimingUtils.showTimedBalloon(tip, 3000);
                passConfirmPass.grabFocus();

            }
        }
    }//GEN-LAST:event_passConfirmPassKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed

        if (String.valueOf(passNewPass.getPassword()).equals(String.valueOf(passConfirmPass.getPassword()))) {
            try {
                new JDBC().putData("UPDATE user SET passWord='" + String.valueOf(passNewPass.getPassword()) + "', tip='" + txtPassTip.getText() + "' WHERE userName='" + Home.userName + "'");
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            BalloonTip tip = new BalloonTip(passConfirmPass, "Confirm password not matched. Plese enter correct Password.", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 3000);
        }
    }//GEN-LAST:event_btnChangePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblUserLevel;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField passConfirmPass;
    private javax.swing.JPasswordField passCurrent;
    private javax.swing.JPasswordField passNewPass;
    private javax.swing.JTextField txtPassTip;
    // End of variables declaration//GEN-END:variables
}
