/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thusitha
 */
public class chequeTransaction extends javax.swing.JInternalFrame {

    /**
     * Creates new form chequeTransaction
     */
    public chequeTransaction() {
        super("Cheque Transaction", false, true, false, true);
        initComponents();
        bankNames();
        getTransaction();
        clear();
        btnPrint.setVisible(false);

    }

    public void bankNames() {
        try {
            ResultSet r = new JDBC().getData("SELECT * FROM bankAccount WHERE type ='" + "Current" + "'");
            Vector v = new Vector();
            v.add("-- Select Bank --");
            while (r.next()) {
                v.add(r.getString("bankName"));
            }
            cmbboxBank.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void getTransaction() {
        DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
        int count = dtm.getRowCount();
        for (int i = 0; i < count; i++) {
            dtm.removeRow(0);
        }
        try {
            ResultSet r = new JDBC().getData("SELECT * FROM chequetrans");
            while (r.next()) {
                Vector v = new Vector();
                v.add(r.getString("chequeNo"));
                v.add(r.getString("accNo"));
                v.add(r.getString("Description"));
                v.add(r.getString("bank"));
                v.add(r.getString("issueDate"));
                v.add(r.getString("depositDate"));
                v.add(r.getString("type"));
                v.add(r.getString("payee"));
                v.add(r.getString("amount"));

                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    Date date = new Date();

    public void clear() {
        cmbboxBank.setSelectedIndex(0);
        cmbboxAccNo.setSelectedIndex(0);
        txtChequeNo.setText("");
        cmbboxChequeType.setSelectedIndex(0);
        txtPayee.setText("");
        txtAmount.setText("");
        txtDescription.setText("");
        txtChequeDate.setDate(date);
        txtDepositDate.setDate(date);

        cmbboxAccNo.setEnabled(false);
        cmbboxbookNo.setEnabled(false);
        txtChequeNo.setEnabled(false);
        cmbboxChequeType.setEnabled(false);
        txtPayee.setEnabled(false);
        txtAmount.setEnabled(false);
        txtDescription.setEnabled(false);
        txtChequeDate.setEnabled(false);
        txtDepositDate.setEnabled(false);
        btnSave.setEnabled(false);
//        btnClear.setEnabled(false);
        btnPrint.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtChequeNo = new javax.swing.JTextField();
        txtPayee = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtChequeDate = new com.toedter.calendar.JDateChooser();
        txtDepositDate = new com.toedter.calendar.JDateChooser();
        btnPrint = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cmbboxChequeType = new javax.swing.JComboBox();
        cmbboxBank = new javax.swing.JComboBox();
        cmbboxAccNo = new javax.swing.JComboBox();
        cmbboxbookNo = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cheque No", "A/C no", "Description", "Bank name", "Issued Date", "Deposit Date", "Type", "Payee", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, 1330, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Cheque Transaction Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/handshake-64.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 42, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel50.setText("Amount");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 170, -1, -1));

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAmount.setToolTipText("");
        txtAmount.setEnabled(false);
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAmountKeyPressed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 165, 293, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Cheque type");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 293, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel53.setText("Cheque Date");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 209, -1, -1));

        txtChequeNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChequeNo.setToolTipText("");
        jPanel1.add(txtChequeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 247, 240, -1));

        txtPayee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPayee.setToolTipText("");
        txtPayee.setEnabled(false);
        txtPayee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayeeKeyPressed(evt);
            }
        });
        jPanel1.add(txtPayee, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 333, 240, -1));

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescription.setToolTipText("");
        txtDescription.setEnabled(false);
        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyPressed(evt);
            }
        });
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 124, 293, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Description");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 127, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Bank");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Account No");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Cheque Book No");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Cheque No");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtChequeDate.setDateFormatString("yyyy-MM-dd");
        txtChequeDate.setEnabled(false);
        txtChequeDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChequeDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChequeDateMouseClicked(evt);
            }
        });
        txtChequeDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChequeDateKeyPressed(evt);
            }
        });
        jPanel1.add(txtChequeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 206, 170, -1));

        txtDepositDate.setDateFormatString("yyyy-MM-dd");
        txtDepositDate.setEnabled(false);
        txtDepositDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDepositDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDepositDateKeyPressed(evt);
            }
        });
        jPanel1.add(txtDepositDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 240, 170, -1));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/printer-32.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, 110, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/save-32.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, 110, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finance/rename-32.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 310, 100, -1));

        cmbboxChequeType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbboxChequeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select cheque type--", "Cash Cheque", "Crossed Cheque" }));
        cmbboxChequeType.setEnabled(false);
        cmbboxChequeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxChequeTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbboxChequeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 293, 240, -1));

        cmbboxBank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbboxBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Bank --" }));
        cmbboxBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxBankActionPerformed(evt);
            }
        });
        jPanel1.add(cmbboxBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 124, 300, -1));

        cmbboxAccNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbboxAccNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Account Number --" }));
        cmbboxAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxAccNoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbboxAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 164, 300, -1));

        cmbboxbookNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbboxbookNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Cheque Book Number --" }));
        cmbboxbookNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxbookNoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbboxbookNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 206, 300, -1));

        jCheckBox1.setText("Edit");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("Payee");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 336, -1, -1));

        jCheckBox2.setText("Edit");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 205, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Deposit Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

//        try {
//            ResultSet r = new JDBC().getData("SELECT status FROM chequeinfo WHERE chequeNo='"+txtChequeNo1.getText()+"' AND status='"+"not issued"+"'");
//            if (r.first()) {
////                save query
//            }else{
////                update query
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        saveData();
        getTransaction();
        clear();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

                clear();
    }//GEN-LAST:event_btnClearActionPerformed

    double balance;
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void cmbboxBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxBankActionPerformed

        cmbboxAccNo.setEnabled(true);
        try {
            ResultSet r = new JDBC().getData("SELECT accNo FROM bankAccount WHERE bankName='" + cmbboxBank.getSelectedItem() + "' and type='current'");
            Vector v = new Vector();
            v.add("-- Select Account Number --");
            while (r.next()) {
                v.add(r.getString("accNo"));
            }
            cmbboxAccNo.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbboxBankActionPerformed

    private void cmbboxAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxAccNoActionPerformed

        cmbboxbookNo.setEnabled(true);
        try {
            ResultSet r = new JDBC().getData("SELECT bookNo FROM chequeBook WHERE accNo='" + cmbboxAccNo.getSelectedItem() + "'");
            Vector v = new Vector();
            v.add("-- Select Cheque Book Number --");
            while (r.next()) {
                v.add(r.getString("bookNo"));
            }
            cmbboxbookNo.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbboxAccNoActionPerformed

    private void cmbboxbookNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxbookNoActionPerformed

        try {
            ResultSet r = new JDBC().getData("SELECT chequeNo FROM chequeinfo WHERE bookNo='" + cmbboxbookNo.getSelectedItem() + "' AND status='" + "not issued" + "'");
            if (r.first()) {
                txtChequeNo.setText(r.getString("chequeNo"));
                cmbboxChequeType.setEnabled(true);
                cmbboxChequeType.grabFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot find any cheque number");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbboxbookNoActionPerformed

    private void cmbboxChequeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxChequeTypeActionPerformed

        txtPayee.setEnabled(true);
        txtPayee.grabFocus();
    }//GEN-LAST:event_cmbboxChequeTypeActionPerformed

    private void txtPayeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayeeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDescription.setEnabled(true);
            txtDescription.grabFocus();
        }
    }//GEN-LAST:event_txtPayeeKeyPressed

    private void txtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAmount.setEnabled(true);
            txtAmount.grabFocus();
        }
    }//GEN-LAST:event_txtDescriptionKeyPressed

    private void txtAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtChequeDate.setEnabled(true);
            txtChequeDate.grabFocus();
        }
    }//GEN-LAST:event_txtAmountKeyPressed

    private void txtChequeDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeDateKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDepositDate.setEnabled(true);
            txtDepositDate.grabFocus();
        }
    }//GEN-LAST:event_txtChequeDateKeyPressed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            saveData();
        }
        getTransaction();
//        clear();
    }//GEN-LAST:event_btnSaveKeyPressed

    private void txtDepositDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepositDateKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSave.setEnabled(true);
            btnSave.grabFocus();
        }
    }//GEN-LAST:event_txtDepositDateKeyPressed

    private void txtChequeDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChequeDateMouseClicked

        if (txtChequeDate.getCalendarButton().isEnabled()) {
            txtDepositDate.setEnabled(true);
            txtDepositDate.grabFocus();
        }
    }//GEN-LAST:event_txtChequeDateMouseClicked

    String selectedChequeNo="";
    String selectedAcountNo="";
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked

        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            int i = JOptionPane.showConfirmDialog(this, "Do you want to edit this record?", "Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
            if (i == 0) {
                int j = jTable4.getSelectedRow();
                selectedChequeNo=jTable4.getValueAt(j, 0).toString();
                selectedAcountNo=jTable4.getValueAt(j, 1).toString();
                
        System.out.println("selectedAccountNo"+selectedAcountNo);
        System.out.println("selectedChequeNo"+selectedChequeNo);
                
                cmbboxBank.setSelectedItem(jTable4.getValueAt(j, 2));
                cmbboxAccNo.setSelectedItem(jTable4.getValueAt(j, 1));
                try {
                    ResultSet r = new JDBC().getData("SELECT bookNo FROM chequeinfo WHERE chequeNo='"+txtChequeNo.getText()+"' AND accNo='"+cmbboxAccNo.getSelectedItem()+"' ");
                    if (r.next()) {
                        cmbboxbookNo.setSelectedItem(r.getString("bookNo"));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                txtChequeNo.setText(jTable4.getValueAt(j, 0).toString());
                cmbboxChequeType.setSelectedItem(jTable4.getValueAt(j, 5));
                txtPayee.setText(jTable4.getValueAt(j, 6).toString());
                txtAmount.setText(jTable4.getValueAt(j, 7).toString());
                
                cmbboxBank.setEnabled(false);
                cmbboxAccNo.setEnabled(false);
                cmbboxbookNo.setEnabled(false);
                txtChequeNo.setEnabled(false);
                cmbboxChequeType.grabFocus();

            } else {

            }
        }

    }//GEN-LAST:event_jTable4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbboxAccNo;
    private javax.swing.JComboBox cmbboxBank;
    private javax.swing.JComboBox cmbboxChequeType;
    private javax.swing.JComboBox cmbboxbookNo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField txtAmount;
    private com.toedter.calendar.JDateChooser txtChequeDate;
    private javax.swing.JTextField txtChequeNo;
    private com.toedter.calendar.JDateChooser txtDepositDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPayee;
    // End of variables declaration//GEN-END:variables

    void saveData() {
        try {

            SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
            String issueDate = sd.format(txtChequeDate.getDate());
            String depositDate = sd.format(txtDepositDate.getDate());
            System.out.println(txtChequeNo.getText());

            ResultSet r = new JDBC().getData("select BA.accNo,BA.balance,CI.chequeNo,CI.status FROM bankAccount BA, chequeinfo CI WHERE BA.accNo=CI.accNo and BA.accNo='" + cmbboxAccNo.getSelectedItem() + "' and CI.chequeNo='" + txtChequeNo.getText() + "'");
            while (r.next()) {
                double balance = Double.parseDouble(r.getString("BA.balance")) - Double.parseDouble(txtAmount.getText());
                if (-50000 < balance) {
                    if (selectedAcountNo.equals(cmbboxAccNo.getSelectedItem()) && selectedChequeNo.equals(txtChequeNo.getText())) {
                        new JDBC().putData("UPDATE chequetrans SET description='"+txtDescription.getText()+"' issueDate='"+issueDate+"', depositDate='"+depositDate+"',type='"+cmbboxChequeType.getSelectedItem()+"', payee='"+txtPayee.getText()+"', amount='"+txtAmount.getText()+"' WHERE chequeNo='"+txtChequeNo.getText()+"' AND accNo='"+cmbboxAccNo.getSelectedItem()+"'");
                    }else{
                        new JDBC().putData("INSERT INTO chequetrans VALUES('" + txtChequeNo.getText() + "','" + cmbboxAccNo.getSelectedItem() + "','" + cmbboxBank.getSelectedItem() + "','" + issueDate + "','" + depositDate + "','" + cmbboxChequeType.getSelectedItem() + "','" + txtPayee.getText() + "','" + txtAmount.getText() + "','"+txtDescription.getText()+"')");
                    
                    }
                    new JDBC().putData("UPDATE bankAccount SET balance='" + String.valueOf(balance) + "' WHERE accNo='" + cmbboxAccNo.getSelectedItem() + "'");
                    new JDBC().putData("UPDATE chequeinfo SET status='" + "issued" + "' WHERE chequeNo='" + txtChequeNo.getText() + "'");
                    JOptionPane.showMessageDialog(this, "Record saved");

                } else {
                    JOptionPane.showMessageDialog(this, "account limit is exceed.");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        clear();
    }

}
