/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Thusitha
 */
public class FinanceReports extends javax.swing.JInternalFrame {

    /**
     * Creates new form FinanaceReports
     */
    public FinanceReports() {
        super("Finance Reports", true, true, true);
        initComponents();
        lblReportType.setVisible(false);
        cmbReportType.setVisible(false);
        pnlSupplier.setVisible(false);
        btnShow.setVisible(false);
        jDateChooser1.setVisible(false);
        jComboBox1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cmbReportType = new javax.swing.JComboBox();
        btnShow = new javax.swing.JButton();
        lblReportType = new javax.swing.JLabel();
        cmbOption = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        pnlSupplier = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        cmbReportType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbReportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReportTypeActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        lblReportType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblReportType.setText("Report Type");

        cmbOption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Option --", "Supplier Payment Reports", "Cheque Transaction", "Cash Book Reports" }));
        cmbOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOptionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Report Title");

        pnlSupplier.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jRadioButton1.setText("Supplier Id");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jRadioButton2.setText("GRN No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jRadioButton3.setText("Date");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlSupplierLayout = new javax.swing.GroupLayout(pnlSupplier);
        pnlSupplier.setLayout(pnlSupplierLayout);
        pnlSupplierLayout.setHorizontalGroup(
            pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSupplierLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton2)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlSupplierLayout.createSequentialGroup()
                        .addGroup(pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlSupplierLayout.setVerticalGroup(
            pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSupplierLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel4.setText("Finance Reports");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblReportType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbOption, 0, 226, Short.MAX_VALUE)
                            .addComponent(cmbReportType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReportType))
                .addGap(44, 44, 44)
                .addComponent(pnlSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed

        Date d = new Date();
        final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        final String dt = sdf.format(d);
        final int i = jTabbedPane1.getTabCount();
//        ImageIcon ii = new ImageIcon(getClass().getResource("/images/finance/loading5.gif"));
        jTabbedPane1.addTab("Loading..", new JPanel().add(new JLabel("Loading")));

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    if (cmbOption.getSelectedItem() == "Supplier Payment Reports") {
                        if (cmbReportType.getSelectedIndex() == 1) {
                            File f = new File("src/reports/AllSupplierPayment.jrxml");
                            SupplierPaymentReport(i, null, dt, dt, f, "All Supplier Payment Details");
                        } else if (cmbReportType.getSelectedIndex() == 2) {
                            File f = new File("src/reports/DaySupplierPaymentReport.jrxml");
                            SupplierPaymentReport(i, "date", dt, dt, f, "Day Report");
                        } else if (cmbReportType.getSelectedIndex() == 3) {
                            if (jRadioButton1.isSelected()) {
                                File f = new File("src/reports/SupplierPaymentReport.jrxml");
                                SupplierPaymentReport(i, "supplier", jComboBox1.getSelectedItem().toString(), dt, f, "Supplier Payment Report");
                            } else if (jRadioButton2.isSelected()) {
                                File f = new File("src/reports/GrnPaymentReport.jrxml");
                                SupplierPaymentReport(i, "grnNo", jComboBox1.getSelectedItem().toString(), dt, f, "GRN Payment Report");
                            } else if (jRadioButton3.isSelected()) {
                                File f = new File("src/reports/DaySupplierPaymentReport.jrxml");
                                SupplierPaymentReport(i, "date", sdf.format(jDateChooser1.getDate()), dt, f, "Report of " + sdf.format(jDateChooser1.getDate()));

                            }
                        }
                    } else if (cmbOption.getSelectedIndex() == 2) {
                        
                        
                    } else if (cmbOption.getSelectedItem() == "Cheque Transaction") {
                        if (cmbReportType.getSelectedIndex() == 1) {
                            File f = new File("src/reports/AllChequeTransactions.jrxml");
                            SupplierPaymentReport(i, null, dt, dt, f, "All Supplier Payment Details");
                        } else if (cmbReportType.getSelectedIndex() == 2) {
                            File f = new File("src/reports/DayChequeTransaction.jrxml");
                            SupplierPaymentReport(i, "date", dt, dt, f, "Today Report");
                        } else if (cmbReportType.getSelectedIndex() == 3) {
                            if (jRadioButton1.isSelected()) {
                                File f = new File("src/reports/SupplierChequeTransactions.jrxml");
                                SupplierPaymentReport(i, "supplier", jComboBox1.getSelectedItem().toString(), dt, f, "Supplier Report");
                            } else if (jRadioButton2.isSelected()) {
                                File f = new File("src/reports/GrnChequeTransactions.jrxml");
                                SupplierPaymentReport(i, "grnNo", jComboBox1.getSelectedItem().toString(), dt, f, "GRN Report");
                            } else if (jRadioButton3.isSelected()) {
                                File f = new File("src/reports/DayChequeTransaction.jrxml");
                                SupplierPaymentReport(i, "date", sdf.format(jDateChooser1.getDate()), dt, f, "Report of " + sdf.format(jDateChooser1.getDate()));

                            }
                        }
                    } else if (cmbOption.getSelectedItem() =="Cash Book Reports") {
                        if (cmbReportType.getSelectedIndex() == 1) {
                            File f = new File("src/reports/AllcashBookReport.jrxml");
                            SupplierPaymentReport(i, null, dt, dt, f, "All Cashbook Details");
                        } else if (cmbReportType.getSelectedIndex() == 2) {
                            File f = new File("src/reports/DayCashBook.jrxml");
                            SupplierPaymentReport(i, "date", dt, dt, f, "Today Report");
                        }
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }).start();
        Thread.currentThread().stop();
    }//GEN-LAST:event_btnShowActionPerformed

    public void SupplierPaymentReport(int i, String para, String dt, String date, File f, String title) throws JRException, Exception {

        Map<String, Object> params = new HashMap<>();
        params.put(para, dt);
        params.put("emp", Home.userName);
        params.put("dt", date);
        JasperReport jasperReport = JasperCompileManager.compileReport(f.toString());
        Connection c = new JDBC().con();
        JasperPrint print = JasperFillManager.fillReport(jasperReport, params, c);
        JRViewer view = new JRViewer(print);
        view.setZoomRatio((float) 1.0);
        jTabbedPane1.setTitleAt(i, title);
        jTabbedPane1.setIconAt(i, null);
        jTabbedPane1.setComponentAt(i, view);
    }

    private void cmbOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOptionActionPerformed

        Vector v = new Vector();
        if (cmbOption.getSelectedIndex() == 0) {
            lblReportType.setVisible(false);
            cmbReportType.setVisible(false);
            btnShow.setVisible(false);

        } else if (cmbOption.getSelectedIndex() == 1) {
            lblReportType.setVisible(true);
            cmbReportType.setVisible(true);
            v.add("-- Select Option --");
            v.add("All Payments");
            v.add("Today Payments");
            v.add("Other");

        } else if (cmbOption.getSelectedIndex() == 2) {
            lblReportType.setVisible(true);
            cmbReportType.setVisible(true);
            v.add("-- Select Option --");
            v.add("All Transactions");
            v.add("Today Transactions");
            v.add("Other");
        } else if (cmbOption.getSelectedIndex() == 3) {
            lblReportType.setVisible(true);
            cmbReportType.setVisible(true);
            v.add("-- Select Option --");
            v.add("All Transactions");
            v.add("Today Transactions");
            v.add("Other");
        } else if (cmbOption.getSelectedIndex() == 4) {
            lblReportType.setVisible(true);
            cmbReportType.setVisible(true);
            v.add("-- Select Option --");
            v.add("All cash Transactions");
            v.add("Today cash Transactions");

        }
        cmbReportType.setModel(new DefaultComboBoxModel(v));
    }//GEN-LAST:event_cmbOptionActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (jRadioButton1.isSelected()) {
            jDateChooser1.setVisible(false);
            jComboBox1.setVisible(true);
            btnShow.setVisible(true);
            Vector v = new Vector();
            try {
                ResultSet r = new JDBC().getData("SELECT DISTINCT(supId) FROM suppay");
                while (r.next()) {
                    v.add(r.getString("supId"));
                }
                jComboBox1.setModel(new DefaultComboBoxModel(v));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        if (jRadioButton2.isSelected()) {
            jDateChooser1.setVisible(false);
            jComboBox1.setVisible(true);
            btnShow.setVisible(true);
            Vector v = new Vector();
            try {
                ResultSet r = new JDBC().getData("SELECT DISTINCT(grnNo) FROM suppay");
                while (r.next()) {
                    v.add(r.getString("grnNo"));
                }
                jComboBox1.setModel(new DefaultComboBoxModel(v));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void cmbReportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReportTypeActionPerformed

        if (cmbReportType.getSelectedIndex() == 0) {
            pnlSupplier.setVisible(false);
            btnShow.setVisible(false);
        } else if (cmbReportType.getSelectedItem().equals("Other")) {
            pnlSupplier.setVisible(true);
        } else {
            pnlSupplier.setVisible(false);
            btnShow.setVisible(true);
        }


    }//GEN-LAST:event_cmbReportTypeActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

        if (jRadioButton3.isSelected()) {
            jDateChooser1.setVisible(true);
            jComboBox1.setVisible(false);
            btnShow.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    void panelShow() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    for (int i = 0; i < 148; i++) {
                        pnlSupplier.setSize(pnlSupplier.getWidth(), i);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbOption;
    private javax.swing.JComboBox cmbReportType;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblReportType;
    private javax.swing.JPanel pnlSupplier;
    // End of variables declaration//GEN-END:variables
}
