/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import net.java.balloontip.styles.RoundedBalloonStyle;
import net.java.balloontip.utils.TimingUtils;
import net.java.balloontip.BalloonTip;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.awt.event.MouseEvent;
import java.awt.RenderingHints;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.util.Hashtable;
import javax.swing.JPanel;
import java.awt.Graphics;
import javax.swing.Timer;
import java.awt.Toolkit;
import java.awt.Image;
import java.awt.Color;
import java.util.Date;
import java.io.File;

/**
 *
 * @author Thusitha
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    Configs con = new Configs();
    String BackupOp = con.getProp("BackupOption");
    static String userName = "Thusitha";
    static String level = "admin";
    static String password = "123";
    static Hashtable<String, Object> addUser = new Hashtable();
    static Hashtable<String, Object> users = new Hashtable<String, Object>();

    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setAccess();
        ImageIcon i = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/new logo.png")));
        setIconImage(i.getImage());

        setTime();
        jPanel1.setVisible(false);
        lblUser.setText("Hi!," + userName);
        ImageIcon ii = new ImageIcon(getClass().getResource("/images/customer_1.png"));
        System.out.println("Home" + Home.userName);
        System.out.println("Home" + Home.password);
        System.out.println("Home" + Home.level);

    }

    public void selectUser() {
        if (level.equals("admin")) {

        }
        if (level.equals("finance manager") || level.equals("manager")) {
            lblInvoice.setVisible(false);
            lblCustomer.setVisible(false);

        } else if (level.equals("stock handler")) {
            lblInvoice.setVisible(false);
            lblEmployee.setVisible(false);
            lblCustomer.setVisible(false);
            lblSupplier.setVisible(false);
            lblFinance.setVisible(false);

        } else if (level.equals("cashier")) {
            lblSupplier.setVisible(false);
            lblFinance.setVisible(false);
            lblEmployee.setVisible(false);

        } else if (level.equals("guest")) {
            lblSupplier.setVisible(false);
            lblFinance.setVisible(false);
            lblEmployee.setVisible(false);
            lblInvoice.setVisible(false);
        }
    }

    public void setAccess() {
        selectUser();
        int y = 100;
        int x = 100;
        if (lblStock.isVisible()) {
            lblStock.setLocation(x, y);
            y += 70;
        }
        if (lblInvoice.isVisible()) {
            lblInvoice.setLocation(x, y);
            y += 70;

        }
        if (lblEmployee.isVisible()) {
            lblEmployee.setLocation(x, y);
            y += 70;

        }
        if (lblCustomer.isVisible()) {
            lblCustomer.setLocation(x, y);
            y += 70;

        }
        if (lblSupplier.isVisible()) {
            lblSupplier.setLocation(x, y);
            y += 70;

        }
        if (lblFinance.isVisible()) {
            lblFinance.setLocation(x, y);
            y += 70;

        }
        if (lblReport.isVisible()) {
            lblReport.setLocation(x, y);
            y += 70;

        }
    }

    void setTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                String time = df.format(d);
                lblClock.setText(time);

            }
        }).start();
    }

    RoundedBalloonStyle style = new RoundedBalloonStyle(10, 5, Color.yellow, Color.yellow);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblPower = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/desktop/back.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(), getHeight(), this);
            }
        };
        lblInvoice = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblFinance = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/powerSelected.png"))); // NOI18N
        lblPower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPowerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPowerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPowerMouseExited(evt);
            }
        });
        jPanel2.add(lblPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, -1, 40));

        lblClock.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setText("Time");
        lblClock.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblClockPropertyChange(evt);
            }
        });
        jPanel2.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 190, 40));

        lblUser.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/user.png"))); // NOI18N
        lblUser.setText("jLabel2");
        lblUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 270, 40));

        lblMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        lblMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMessageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMessageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMessageMouseExited(evt);
            }
        });
        jPanel2.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/task.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 40));

        lblInvoice.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/invoice  default.png"))); // NOI18N
        lblInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInvoiceMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblInvoice);
        lblInvoice.setBounds(100, 170, 530, 70);

        lblStock.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/stock default.png"))); // NOI18N
        lblStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStockMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblStock);
        lblStock.setBounds(100, 100, 530, 70);

        lblEmployee.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/employee default.png"))); // NOI18N
        lblEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblEmployee);
        lblEmployee.setBounds(100, 240, 530, 70);

        lblSupplier.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/supplier default.png"))); // NOI18N
        lblSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblSupplier);
        lblSupplier.setBounds(100, 380, 530, 70);

        lblCustomer.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/customer default.png"))); // NOI18N
        lblCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomerMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblCustomer);
        lblCustomer.setBounds(100, 310, 530, 70);

        lblReport.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/report default.png"))); // NOI18N
        lblReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblReport);
        lblReport.setBounds(100, 520, 530, 70);

        lblFinance.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 40)); // NOI18N
        lblFinance.setForeground(new java.awt.Color(255, 255, 255));
        lblFinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainMenu/finance default.png"))); // NOI18N
        lblFinance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFinance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFinanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFinanceMouseExited(evt);
            }
        });
        jDesktopPane2.add(lblFinance);
        lblFinance.setBounds(100, 450, 530, 70);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jDesktopPane2.add(jPanel1);
        jPanel1.setBounds(610, 110, 630, 470);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1366, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String title = "";
    private void lblInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/invoice.png"));
        lblInvoice.setIcon(ii);
    }//GEN-LAST:event_lblInvoiceMouseEntered

    private void lblInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseExited

        if (title.equals("Invoice")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/invoice.png"));
            lblInvoice.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/invoice  default.png"));
            lblInvoice.setIcon(ii);
        }

    }//GEN-LAST:event_lblInvoiceMouseExited

    void SetUnvisible() {
        stock.setVisible(false);
        customer.setVisible(false);
    }
    private void lblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(stock);
            stock.setSize(630, 490);
            stock.setLocation(0, 0);
            stock.setVisible(true);
            title = "Stock";

        } else if (jPanel1.isVisible() && !(title.equals("Stock"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(stock);
            stock.setSize(630, 490);
            stock.setLocation(0, 0);
            stock.setVisible(true);
            title = "Stock";

        } else if (jPanel1.isVisible() && (stock.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            stock.setSize(0, 0);
            stock.setLocation(0, 0);
            jDesktopPane1.removeAll();
            stock.setVisible(false);
            title = "";
        }

        hideMenu(evt);

    }//GEN-LAST:event_lblStockMouseClicked

    private void lblStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/stock.png"));
        lblStock.setIcon(ii);
    }//GEN-LAST:event_lblStockMouseEntered

    private void lblStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseExited

        if (title.equals("Stock")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/stock.png"));
            lblStock.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/stock default.png"));
            lblStock.setIcon(ii);
        }
    }//GEN-LAST:event_lblStockMouseExited

    private void lblEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/employee.png"));
        lblEmployee.setIcon(ii);
    }//GEN-LAST:event_lblEmployeeMouseEntered

    private void lblEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseExited

        if (title.equals("Employee")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/employee.png"));
            lblEmployee.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/employee default.png"));
            lblEmployee.setIcon(ii);
        }
    }//GEN-LAST:event_lblEmployeeMouseExited

    private void lblSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/supplier.png"));
        lblSupplier.setIcon(ii);
    }//GEN-LAST:event_lblSupplierMouseEntered

    private void lblSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseExited

        if (title.equals("Supplier")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/supplier.png"));
            lblSupplier.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/supplier default.png"));
            lblSupplier.setIcon(ii);
        }
    }//GEN-LAST:event_lblSupplierMouseExited

    private void lblFinanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinanceMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(finance);
            finance.setSize(630, 490);
            finance.setLocation(0, 0);
            finance.setVisible(true);
            title = "Finance";

        } else if (jPanel1.isVisible() && !(title.equals("Finance"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(finance);
            finance.setSize(630, 490);
            finance.setLocation(0, 0);
            finance.setVisible(true);
            title = "Finance";

        } else if (jPanel1.isVisible() && (finance.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            finance.setVisible(false);
            title = "";
        }
        hideMenu(evt);

    }//GEN-LAST:event_lblFinanceMouseClicked

    private void lblFinanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinanceMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/finance.png"));
        lblFinance.setIcon(ii);
    }//GEN-LAST:event_lblFinanceMouseEntered

    private void lblFinanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinanceMouseExited

        if (title.equals("Finance")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/finance.png"));
            lblFinance.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/finance default.png"));
            lblFinance.setIcon(ii);
        }
    }//GEN-LAST:event_lblFinanceMouseExited

    private void lblCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/customer.png"));
        lblCustomer.setIcon(ii);
    }//GEN-LAST:event_lblCustomerMouseEntered

    private void lblCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseExited

        if (title.equals("Customer")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/customer.png"));
            lblCustomer.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/customer default.png"));
            lblCustomer.setIcon(ii);
        }
    }//GEN-LAST:event_lblCustomerMouseExited

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/report.png"));
        lblReport.setIcon(ii);
    }//GEN-LAST:event_lblReportMouseEntered

    private void lblReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseExited

        if (title.equals("Report")) {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/report.png"));
            lblReport.setIcon(ii);
        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/mainMenu/report default.png"));
            lblReport.setIcon(ii);
        }
    }//GEN-LAST:event_lblReportMouseExited

    private void lblPowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerMouseClicked

        System.exit(1);
    }//GEN-LAST:event_lblPowerMouseClicked

    private void lblPowerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/power.png"));
        lblPower.setIcon(ii);
    }//GEN-LAST:event_lblPowerMouseEntered

    private void lblPowerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPowerMouseExited

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/powerSelected.png"));
        lblPower.setIcon(ii);
    }//GEN-LAST:event_lblPowerMouseExited

    Date d = new Date();
    SimpleDateFormat sd = new SimpleDateFormat("hh-mm-ssa");
    private void lblClockPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblClockPropertyChange

        sd.format(d);
        if (con.getProp("BackupOption").equals("Auto") && con.getProp("AutoBackupTime").equals(lblClock.getText())) {

            String sql1 = "C:\\Program Files\\MySQL\\MySQL Server 5.5\\bin\\mysqldump -uroot -p1234 buildpc -r" + con.getProp("AutoBackupLocation") + sd.format(d) + ".sql";
            try {
                System.out.println(sql1);
                Runtime.getRuntime().exec(sql1);
            } catch (Exception e) {
                e.printStackTrace();
            }
            BalloonTip tip = new BalloonTip(lblClock, "Database backup is completed", style, false);
            tip.setVisible(true);
            TimingUtils.showTimedBalloon(tip, 3000);

        }
        System.gc();
    }//GEN-LAST:event_lblClockPropertyChange

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered

        lblUser.setOpaque(true);
        lblUser.setBackground(new Color(51, 51, 51));
        ImageIcon ii = new ImageIcon(getClass().getResource("/images/desktop/userSelected.png"));
        lblUser.setIcon(ii);
    }//GEN-LAST:event_lblUserMouseEntered

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited

        if (usermenu.isVisible()) {
            lblUser.setOpaque(true);
            lblUser.setBackground(new Color(51, 51, 51));
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/desktop/userSelected.png"));
            lblUser.setIcon(ii);

        } else {
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/desktop/user.png"));
            lblUser.setIcon(ii);
            lblUser.setOpaque(false);
        }
    }//GEN-LAST:event_lblUserMouseExited

    StockMenu stock = new StockMenu();
    CustomerMenu customer = new CustomerMenu();
    EmployeeMenu employee = new EmployeeMenu();
    SupplierMenu supplier = new SupplierMenu();
    FinanceMenu finance = new FinanceMenu();
    ReportMenu report = new ReportMenu();
    InvoiceMenu invoice = new InvoiceMenu();
    private void lblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvoiceMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(invoice);
            invoice.setSize(630, 490);
            invoice.setLocation(0, 0);
            invoice.setVisible(true);
            title = "Invoice";

        } else if (jPanel1.isVisible() && !(title.equals("Invoice"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(invoice);
            invoice.setSize(630, 490);
            invoice.setLocation(0, 0);
            invoice.setVisible(true);
            title = "Invoice";

        } else if (jPanel1.isVisible() && (invoice.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            invoice.setVisible(false);
            title = "";
        }
        hideMenu(evt);


    }//GEN-LAST:event_lblInvoiceMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(employee);
            employee.setSize(630, 490);
            employee.setLocation(0, 0);
            employee.setVisible(true);
            title = "Employee";

        } else if (jPanel1.isVisible() && !(title.equals("Employee"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(employee);
            employee.setSize(630, 490);
            employee.setLocation(0, 0);
            employee.setVisible(true);
            title = "Employee";

        } else if (jPanel1.isVisible() && (employee.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            employee.setVisible(false);
            title = "";
        }
        hideMenu(evt);
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(customer);
            customer.setSize(630, 490);
            customer.setLocation(0, 0);
            customer.setVisible(true);
            title = "Customer";

        } else if (jPanel1.isVisible() && !(title.equals("Customer"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(customer);
            customer.setSize(630, 490);
            customer.setLocation(0, 0);
            customer.setVisible(true);
            title = "Customer";

        } else if (jPanel1.isVisible() && (customer.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            customer.setVisible(false);
            title = "";
        }
        hideMenu(evt);
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(supplier);
            supplier.setSize(630, 490);
            supplier.setLocation(0, 0);
            supplier.setVisible(true);
            title = "Supplier";

        } else if (jPanel1.isVisible() && !(title.equals("Supplier"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(supplier);
            supplier.setSize(630, 490);
            supplier.setLocation(0, 0);
            supplier.setVisible(true);
            title = "Supplier";

        } else if (jPanel1.isVisible() && (supplier.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            supplier.setVisible(false);
            title = "";
        }
        hideMenu(evt);
    }//GEN-LAST:event_lblSupplierMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked

        if (!(jPanel1.isVisible())) {
            jDesktopPane1.removeAll();
            panelEnter();
            jDesktopPane1.add(report);
            report.setSize(630, 490);
            report.setLocation(0, 0);
            report.setVisible(true);
            title = "Report";

        } else if (jPanel1.isVisible() && !(title.equals("Report"))) {
            jDesktopPane1.removeAll();
            panelExit();
            panelEnter();
            jDesktopPane1.add(report);
            report.setSize(630, 490);
            report.setLocation(0, 0);
            report.setVisible(true);
            title = "Report";

        } else if (jPanel1.isVisible() && (report.isVisible())) {
            jDesktopPane1.removeAll();
            panelExit();
            report.setVisible(false);
            title = "";
        }
        hideMenu(evt);
    }//GEN-LAST:event_lblReportMouseClicked

    userManagment user = new userManagment();
    static MenuUser usermenu = new MenuUser();
    static byte userCount = 1;
    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked

        MenuUser.lblUsername.setText(userName);
        MenuUser.lblUserLevel.setText(level);
        setImage();
        if (userCount == 1) {
            usermenu.setVisible(true);
            usermenu.setLocation(850, 40);
            if (level.equals("admin")) {
                usermenu.setSize(270, 300);
            } else {
                usermenu.setSize(270, 213);
            }
            userCount = 2;
        } else if (userCount == 2) {
            usermenu.dispose();
            userCount = 1;
        }

    }//GEN-LAST:event_lblUserMouseClicked

    private void lblMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessageMouseClicked

        Messages msg = new Messages();
        Home.jDesktopPane2.add(msg);
        msg.setVisible(true);
    }//GEN-LAST:event_lblMessageMouseClicked

    private void lblMessageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessageMouseEntered

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/notificationSelect.png"));
        ii.getImage();
        lblMessage.setIcon(ii);
    }//GEN-LAST:event_lblMessageMouseEntered

    private void lblMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessageMouseExited

        ImageIcon ii = new ImageIcon(getClass().getResource("/images/notification.png"));
        ii.getImage();
        lblMessage.setIcon(ii);
    }//GEN-LAST:event_lblMessageMouseExited

    BufferedImage image = null;

    public void setImage() {
        try {
            image = ImageIO.read(new File(con.getProp(userName)));
            ImageIcon ii = new ImageIcon(ScaledImage(image, MenuUser.lblUserImage.getWidth(), MenuUser.lblUserImage.getHeight()));
            MenuUser.lblUserImage.setIcon(ii);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private Image ScaledImage(Image img, int w, int h) {

        BufferedImage resizedImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedImage;

    }

    int iconMenuX;
    JPanel panel;
    byte custMenuCount = 0;

    int powerMenuCount = 0;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblFinance;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblSupplier;
    public static javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    public void panelEnter() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {

                    for (int i = 500; i < 620; i++) {
                        jPanel1.setLocation(i, 110);
                        Thread.sleep(1);
                        if (i == 600) {
                            jPanel1.setVisible(true);
                        }
                    }
                    Thread.currentThread().stop();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    public void panelExit() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    for (int i = 620; i < 700; i++) {
                        jPanel1.setLocation(i, 110);
                        Thread.sleep(1);
                        if (i == 640) {
                            jPanel1.setVisible(false);
                        }
                    }
//                    jPanel1.setVisible(false);
                    Thread.currentThread().stop();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    public void hideMenu(MouseEvent evt) {
        lblStockMouseExited(evt);
        lblInvoiceMouseExited(evt);
        lblEmployeeMouseExited(evt);
        lblCustomerMouseExited(evt);
        lblSupplierMouseExited(evt);
        lblReportMouseExited(evt);
        lblFinanceMouseExited(evt);
    }
}
