/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vv
 */
public class Invoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form Invoice
     */
    static int openFrameCount = 0;
    static final int xOffset = 30, yOffset = 30;
    Vector<String> v = new Stack<String>();
    JTextField tx;
    Vector<String> v1 = new Stack<String>();
    JTextField tx1;
    private boolean hide_flag = false;

    public Invoice() {
        super("New Invoice" + (++openFrameCount),
                true, //resizable
                false, //closable
                true, //maximizable
                true);//iconifiable

        //...Create the GUI and put it in the window...
        //...Then set the window size or call pack...
        setSize(300, 300);

        //Set the window's location.
        setLocation(xOffset * openFrameCount, yOffset * openFrameCount);

        initComponents();

        in_no();
        gen_Datetime();
        autoSuggest();
        autoserial();
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        txt_id.setEnabled(false);
        txt_qty.setEnabled(false);
        txt_remainqty.setEnabled(false);
        txt_rep.setText(Home.userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_invoiceno = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txt_rep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cusid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_qty = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_remainqty = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        radio_barcode = new javax.swing.JRadioButton();
        radio_name = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        txt_discount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_nettotal = new javax.swing.JTextField();
        txt_payment = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sales - Invoice");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 91, 144, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Invoice No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, 76, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Rep");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, -1, -1));

        txt_invoiceno.setEditable(false);
        txt_invoiceno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_invoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 130, 180, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 160, 180, -1));

        txt_rep.setEditable(false);
        txt_rep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_rep.setText("Olympus");
        jPanel1.add(txt_rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 190, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Customer:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 141, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Costomer ID / Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Method");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txt_cusid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cusidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 190, -1));

        jPanel2.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ", "Item Description", "Qty", "Unit Price", "Amount", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 245, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/barcode-32.png"))); // NOI18N
        jLabel9.setText("Add Items");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Barcode/Serial:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 38, -1, 30));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel3.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, 232, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Name:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 100, 53, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/good_decision-32.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setToolTipText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 165, 102, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/bad_decision-32.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.setToolTipText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, -1, -1));

        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qtyKeyTyped(evt);
            }
        });
        jPanel3.add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 72, 72, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Qty:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 39, 32, -1));

        txt_remainqty.setEditable(false);
        jPanel3.add(txt_remainqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 100, 72, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Remain in stock:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 232, -1));

        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 134, 72, -1));

        buttonGroup1.add(radio_barcode);
        radio_barcode.setOpaque(false);
        radio_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_barcodeActionPerformed(evt);
            }
        });
        jPanel3.add(radio_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, -1, 32));

        buttonGroup1.add(radio_name);
        radio_name.setOpaque(false);
        radio_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_nameMouseClicked(evt);
            }
        });
        radio_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_nameActionPerformed(evt);
            }
        });
        jPanel3.add(radio_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 98, -1, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 245, 340, 220));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Sub Total  Rs");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 120, -1));

        txt_subtotal.setEditable(false);
        txt_subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_subtotal.setText("0");
        jPanel1.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 172, -1));

        txt_discount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_discount.setText("0");
        txt_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_discountActionPerformed(evt);
            }
        });
        txt_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_discountKeyTyped(evt);
            }
        });
        jPanel1.add(txt_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 172, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Discount   Rs");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 120, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Net Total  Rs");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 110, -1));

        txt_nettotal.setEditable(false);
        txt_nettotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nettotal.setText("0");
        txt_nettotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nettotalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nettotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 172, -1));

        txt_payment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_payment.setText("0");
        txt_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_paymentKeyTyped(evt);
            }
        });
        jPanel1.add(txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 580, 210, -1));

        txt_balance.setEditable(false);
        txt_balance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_balance.setText("0");
        jPanel1.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 620, 210, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Payment   Rs");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 160, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Balance     Rs");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, 170, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Check" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("  BuildPC Computer Systems");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 680, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/disapprove-32.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.setToolTipText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/make_dicision-32.png"))); // NOI18N
        jButton5.setText("Refresh");
        jButton5.setToolTipText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/approve-32.png"))); // NOI18N
        jButton6.setText("Done");
        jButton6.setToolTipText("Done");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 340, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/buildPcLogo.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 140, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 1367, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void autoSuggest() {
        try {
            Class.forName("com.mysql.jdbc.Connection");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/build_final", "root", "1234");
            ResultSet r = con.createStatement().executeQuery("SELECT item_des FROM items where item_id IN(select DISTINCT(item_id) from stock where qty>0)");

            jComboBox2.removeAllItems();
            r.first();
            if (jComboBox2.getItemCount() == 0) {
                do {
                    jComboBox2.addItem(r.getString("item_des"));
                    v.addElement(r.getString("item_des"));
                    jComboBox2.addItemListener(new ItemListener() {

                        @Override
                        public void itemStateChanged(ItemEvent ie) {
                            if (ie.getStateChange() == ItemEvent.SELECTED) {
                                jComboBox2.getSelectedIndex();
                            }
                        }
                    });

                } while (r.next());
            } else {
                jComboBox2.addItem("NOOOOO");
            }
        } catch (Exception e) {
            e.getMessage();
        }
        jComboBox2.setEditable(true);
        tx = (JTextField) jComboBox2.getEditor().getEditorComponent();
        tx.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        String text = tx.getText().toUpperCase();
                        if (text.length() == 0) {
                            jComboBox2.hidePopup();
                            setModel(new DefaultComboBoxModel(v), "");
                        } else {
                            DefaultComboBoxModel m = getSuggest(v, text);
                            if (m.getSize() == 0) {
                                jComboBox2.hidePopup();
                            } else {
                                setModel(m, text);
                                jComboBox2.showPopup();
                            }
                        }
                    }
                });

            }

            @Override
            public void keyPressed(KeyEvent e) {
                String text = tx.getText();
                int code = e.getKeyCode();
                if (code == KeyEvent.VK_ENTER) {
                    if (v.contains(text)) {
                        // v.addElement(text);
                        jComboBox2.hidePopup();
                        jComboBox2.setSelectedItem(text);
                    }
                    hide_flag = true;
                } else if (code == KeyEvent.VK_ESCAPE) {
                    hide_flag = true;
                } else if (code == KeyEvent.VK_RIGHT) {
                    for (int i = 0; i < v.size(); i++) {
                        String str = (String) v.elementAt(i);
                        if (str.startsWith(text)) {
                            tx.setText(str);
                        }
                    }
                }
            }
        });

    }

    private void setModel(DefaultComboBoxModel mdl, String str) {
        jComboBox2.setModel(mdl);
        tx.setText(str);
    }

    private DefaultComboBoxModel getSuggest(List<String> list, String text) {
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String s : list) {
            if (s.startsWith(text)) {
                m.addElement(s);
            }
        }
        return m;
    }

    public void autoserial() {
        try {
            Class.forName("com.mysql.jdbc.Connection");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/build_final", "root", "1234");
            ResultSet r = con.createStatement().executeQuery("SELECT sk.*,it.* FROM stock AS sk,items AS it where  sk.item_id = it.item_id AND it.item_des LIKE'" + jComboBox2.getSelectedItem() + "'");

            jComboBox3.removeAllItems();
            r.first();
            if (jComboBox3.getItemCount() == 0) {
                do {
                    jComboBox3.addItem(r.getString("serial"));
                    v.addElement(r.getString("serial"));
                    jComboBox3.addItemListener(new ItemListener() {

                        @Override
                        public void itemStateChanged(ItemEvent ie) {
                            if (ie.getStateChange() == ItemEvent.SELECTED) {
                                jComboBox3.getSelectedIndex();
                            }
                        }
                    });

                } while (r.next());
            } else {
                jComboBox3.addItem("NOOOOO");
            }
        } catch (Exception e) {
            e.getMessage();
        }
        jComboBox3.setEditable(true);
        tx1 = (JTextField) jComboBox3.getEditor().getEditorComponent();
        tx1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        String text = tx1.getText().toUpperCase();
                        if (text.length() == 0) {
                            jComboBox3.hidePopup();
                            setModel1(new DefaultComboBoxModel(v1), "");
                        } else {
                            DefaultComboBoxModel m = getSuggest1(v1, text);
                            if (m.getSize() == 0) {
                                jComboBox3.hidePopup();
                            } else {
                                setModel1(m, text);
                                jComboBox3.showPopup();
                            }
                        }
                    }
                });

            }

            @Override
            public void keyPressed(KeyEvent e) {
                String text = tx1.getText();
                int code = e.getKeyCode();
                if (code == KeyEvent.VK_ENTER) {
                    if (v1.contains(text)) {
                        // v.addElement(text);
                        jComboBox3.hidePopup();
                        jComboBox3.setSelectedItem(text);
                    }
                    hide_flag = true;
                } else if (code == KeyEvent.VK_ESCAPE) {
                    hide_flag = true;
                } else if (code == KeyEvent.VK_RIGHT) {
                    for (int i = 0; i < v1.size(); i++) {
                        String str = (String) v1.elementAt(i);
                        if (str.startsWith(text)) {
                            tx1.setText(str);
                        }
                    }
                }
            }
        });

    }

    private void setModel1(DefaultComboBoxModel mdl, String str) {
        jComboBox2.setModel(mdl);
        tx1.setText(str);
    }

    private DefaultComboBoxModel getSuggest1(List<String> list, String text) {
        DefaultComboBoxModel m = new DefaultComboBoxModel();
        for (String s : list) {
            if (s.startsWith(text)) {
                m.addElement(s);
            }
        }
        return m;
    }

    void gen_Datetime() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        final String dt = s.format(d);

        new javax.swing.Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d1 = new Date();
                SimpleDateFormat df1 = new SimpleDateFormat("hh:mm:ss a");
                String tm = df1.format(d1);

                jTextField2.setText(dt + " " + tm);
            }
        }).start();
    }

    public void in_no() {
        try {
            ResultSet r = new JDBC().getData("SELECT COUNT(invoice_no) AS row_count FROM invoice");
            while (r.next()) {
                int row = Integer.parseInt(r.getString("row_count"));
                int id = row + 1;
                String no = "Inv00000" + id;
                txt_invoiceno.setText(no);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void txt_cusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cusidActionPerformed

    private void txt_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_discountActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed
    private void add_to_table(String id, String q) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int rowc = jTable1.getRowCount();
        int qty = Integer.parseInt(q);
        try {
            ResultSet r = new JDBC().getData("SELECT sk.*,it.* FROM stock AS sk,items AS it where  sk.item_id = it.item_id AND sk.serial LIKE'" + id + "'");

            while (r.next()) {
                int qty_stock = Integer.parseInt(r.getString("qty"));
                if (qty > qty_stock) {
                    JOptionPane.showMessageDialog(this, "No QTY.....");
                } else {
                    int remain_qty = qty_stock - qty;
                    String remain_qty1 = remain_qty + "";
                    txt_remainqty.setText(remain_qty1);
                    String des = r.getString("item_des") + "_" + r.getString("warranty");
                    Vector v = new Vector();
                    v.add(r.getString("serial"));
                    v.add(des);
                    v.add(2, qty);
                    v.add(3, r.getDouble("price"));

                    Double amount = qty * r.getDouble("price");
                    v.add(4, amount);
                    v.add(5, "0");
                    dtm.addRow(v);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Can't Add.....");
        }

    }

    void addtotable() {
        if (radio_barcode.isSelected()) {

            add_to_table(txt_id.getText(), txt_qty.getText());

        } else if (radio_name.isSelected()) {
            String name = JOptionPane.showInputDialog(this, "How many QTY....?");
            add_to_table(jComboBox3.getSelectedItem().toString(), name);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a item.....");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String serial = "";
        if (radio_barcode.isSelected()) {
            serial = txt_id.getText();
        } else if (radio_name.isSelected()) {
            serial = jComboBox3.getSelectedItem().toString();
        }

        if (isExist(serial)) {
            addtotable();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        dtm.removeRow(i);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' & c <= '9') {
        } else {
            evt.consume();

        }
    }//GEN-LAST:event_txt_qtyKeyTyped
    private void ref() {
        int rows = jTable1.getRowCount();
        double total = 0;
        for (int i = 0; i < rows; i++) {
            total += (Double.parseDouble(jTable1.getValueAt(i, 4).toString()));
        }

        String s = total + "";
        txt_subtotal.setText(s);

        double discount = 0;
        for (int i = 0; i < rows; i++) {
            discount += (Double.parseDouble(jTable1.getValueAt(i, 5).toString()));
        }

        String s1 = discount + "";
        txt_discount.setText(s1);

        double nettotal = total - discount;
        String s2 = nettotal + "";
        txt_nettotal.setText(s2);

        double d = Double.parseDouble(txt_payment.getText());
        double d1 = d - nettotal;
        String s3 = d1 + "";
        txt_balance.setText(s3);

    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ref();
    }//GEN-LAST:event_jButton5ActionPerformed
    private void save() {
        try {
            new JDBC().putData("insert into invoice values('" + txt_invoiceno.getText() + "','" + txt_cusid.getText() + "','" + txt_rep.getText() + "','" + jComboBox1.getSelectedItem() + "','" + txt_payment.getText() + "','" + jTextField2.getText() + "','" + "Sold" + "')");
            JOptionPane.showMessageDialog(this, "Saved !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "cant Save ! "
                    + "Check the information again...");
            e.printStackTrace();
        }

        int rowc = jTable1.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < rowc; i++) {
            String serial = (String) dtm.getValueAt(i, 0);
            String item_des = (String) dtm.getValueAt(i, 1);

            try {
                ResultSet r = new JDBC().getData("SELECT * FROM stock where serial='" + serial + "'");
                while (r.next()) {
                    int qty_stock = Integer.parseInt(r.getString("qty"));
                    int qty1 = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
                    int new_qty = qty_stock - qty1;
                    new JDBC().putData("UPDATE stock SET qty='" + new_qty + "' where serial='" + dtm.getValueAt(i, 0) + "'");
                }

                new JDBC().putData("INSERT INTO invoice_info VALUES('" + txt_invoiceno.getText() + "','" + serial + "','" + item_des + "','" + dtm.getValueAt(i, 2) + "','" + dtm.getValueAt(i, 3) + "','" + dtm.getValueAt(i, 5) + "','" + "Sold" + "')");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "cant Save ! "
                        + "Check the information again...");
            }
        }
        JOptionPane.showMessageDialog(this, "Saved ! report is processing");
    }

    void rep() {
        try {
            String reportSourse = "src\\reports\\invoice.jrxml";
            java.util.Map<String, Object> params = new HashMap<String, Object>();
            params.put("item serial", txt_invoiceno.getText());
            JasperReport jReport = JasperCompileManager.compileReport(reportSourse);
            JasperPrint jp = JasperFillManager.fillReport(jReport, params, new JDBC().con());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int i = JOptionPane.showConfirmDialog(this, "Are you sure....?");
        if (i == 0) {
            in_no();
            ref();
            String s = txt_payment.getText();

            if ("0".equals(s)) {
                String pay = JOptionPane.showInputDialog(this, "Payment....?");
                txt_payment.setText(pay);
                ref();
                save();
            } else {
                save();
            }
            rep();

        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        autoserial();
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void radio_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_barcodeActionPerformed
        if (radio_barcode.isSelected()) {
            txt_id.setEnabled(true);
            txt_qty.setEnabled(true);
            txt_remainqty.setEnabled(true);
            jComboBox2.setEnabled(false);
            jComboBox3.setEnabled(false);
        } else {
            txt_id.setEnabled(false);
            txt_qty.setEnabled(false);
            txt_remainqty.setEnabled(false);
        }
    }//GEN-LAST:event_radio_barcodeActionPerformed

    private void radio_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_nameMouseClicked

    }//GEN-LAST:event_radio_nameMouseClicked

    private void radio_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_nameActionPerformed
        if (radio_name.isSelected()) {
            jComboBox2.setEnabled(true);
            jComboBox3.setEnabled(true);
            txt_id.setEnabled(false);
            txt_qty.setEnabled(false);
            txt_remainqty.setEnabled(false);
        } else {
            jComboBox2.setEnabled(false);
            jComboBox3.setEnabled(false);
        }
    }//GEN-LAST:event_radio_nameActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        autoserial();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txt_nettotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nettotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nettotalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Are you sure about close this INVOICE....?");
        if (i == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_paymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_paymentKeyTyped

    private void txt_discountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_discountKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_discountKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton radio_barcode;
    private javax.swing.JRadioButton radio_name;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_cusid;
    private javax.swing.JTextField txt_discount;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_invoiceno;
    private javax.swing.JTextField txt_nettotal;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_remainqty;
    private javax.swing.JTextField txt_rep;
    private javax.swing.JTextField txt_subtotal;
    // End of variables declaration//GEN-END:variables

    private boolean isExist(String serial) {
        boolean cont = true;
        int rows = jTable1.getRowCount();
        for (int i = 0; i < rows; i++) {
            String se = jTable1.getValueAt(i, 0).toString();
            if (se.equals(serial)) {
                JOptionPane.showMessageDialog(this, "This item is Already Added !");
                cont = false;
            }
        }
        return cont;
    }
}
