/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vv
 */
public class Invoice_details extends javax.swing.JInternalFrame {

    /**
     * Creates new form Invoice_details
     */
        static int openFrameCount = 0;
        static final int xOffset = 30, yOffset = 30;
    
    public Invoice_details() {
        super("Invoice Details" + (++openFrameCount), 
              true, //resizable
              true, //closable
              true, //maximizable
              true);//iconifiable

        //...Create the GUI and put it in the window...

        //...Then set the window size or call pack...
        setSize(300,300);

        //Set the window's location.
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        initComponents();
        ref();
    }
    public Invoice_details(String invoice){
        super("Invoice Details",true,true,true,true);
        initComponents();
        txt_search.setText(invoice);
        jButton3ActionPerformed(null);
        jTable1.setRowSelectionInterval(0, 0);
        jTable1MouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 720));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice no.", "Customer ID", "Rep ID", "Date", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 93, 701, 540));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setToolTipText("");
        jPanel2.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 320, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Invoice no", "Customer ID" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 145, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search-32.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Invoice Details");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 310, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/invoice-64.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1330, 71));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/sinchronize-32.png"))); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 139, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/invoice-32.png"))); // NOI18N
        jButton2.setText("View Invoice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 139, -1));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Click Invoice to view Report");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(240, 240, 240))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report ", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 630, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ref(){
         DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
                    int rowcount=jTable1.getRowCount();
        
                    for (int i = 0; i <rowcount; i++) {
                     dtm.removeRow(0);
                    }
        try {
            ResultSet r = new JDBC().getData("SELECT * FROM invoice");

            while(r.next()){

                Vector v=new Vector();
                v.add(r.getString("invoice_no"));
                v.add(r.getString("customer_id"));
                v.add(r.getString("rep_id"));
                v.add(r.getString("date_time"));
                v.add(r.getString("status"));  
                  
                dtm.addRow(v);
            }
        } catch (Exception e) {
                e.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     ref();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    public void search(String sql){
        
                    DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
                    int rowcount=jTable1.getRowCount();
        
                    for (int i = 0; i <rowcount; i++) {
                     dtm.removeRow(0);
                    }
                    
                    try {
                        ResultSet r =  new JDBC().getData("SELECT * from invoice WHERE"+sql);
                        
                            while(r.next()){

                            Vector v=new Vector();
                            v.add(r.getString("invoice_no"));
                            v.add(r.getString("customer_id"));
                            v.add(r.getString("rep_id"));
                            v.add(r.getString("date_time"));
                            v.add(r.getString("status"));  
                             
                            dtm.addRow(v);
            }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "No Result");
                    }
    
    }
     public void report() {
                try {
                    
                     DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
                     int i=jTable1.getSelectedRow();
                     String s=jTable1.getValueAt(i, 0).toString();
                    
                     
                     String reportSourse="src\\reports\\invoice.jrxml";
                     Map<String,Object> para = new HashMap<String,Object>();
                     para.put("item serial", s);
                     JasperReport jasperReport = JasperCompileManager.compileReport(reportSourse);
                     JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, para,new JDBC().con());
                     JRViewer j = new JRViewer(jasperPrint);
                     jTabbedPane1.setComponentAt(0,j);
                     jTabbedPane1.setSelectedIndex(0);
                     jTabbedPane1.setTitleAt(0, "Invoice Report");
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
           report();
           
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s=jComboBox1.getSelectedItem().toString();
        String keyword=txt_search.getText();
        String sql="";

        if (keyword!=null) {

            if(s=="Invoice no"){
                sql = " invoice_no like '"+"%"+keyword+"%"+"'";
                search(sql);
            }
            if(s=="Customer ID"){
                sql = " customer_id like '"+"%"+keyword+"%"+"'";
                search(sql);
            }
          }else{JOptionPane.showMessageDialog(this, "No result");} 

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedrow=jTable1.getSelectedRow();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        String id=(String)dtm.getValueAt(selectedrow,0);

        old_invoice o=new old_invoice();
        Home.jDesktopPane2.add(o);
        o.oldinvoice(id);
        o.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
