/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import static interfaces.Home.lblUser;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Thusitha
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    Configs con = new Configs();
static String userName = "";
static String level = "";
    public MenuUser() {
        initComponents();
        lblUsername.setText(userName);
        lblUserLevel.setText(level);
        System.out.println("Menu" +userName);
        System.out.println(level);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUserImage = new javax.swing.JLabel();
        lblOp4 = new javax.swing.JLabel();
        lblOp1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUserLevel = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblOp3 = new javax.swing.JLabel();
        lblOp2 = new javax.swing.JLabel();
        lblOp5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblUserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desktop/user.png"))); // NOI18N

        lblOp4.setBackground(new java.awt.Color(51, 51, 51));
        lblOp4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblOp4.setForeground(new java.awt.Color(255, 255, 255));
        lblOp4.setText("User Manager");
        lblOp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOp4.setOpaque(true);
        lblOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOp4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOp4MouseExited(evt);
            }
        });

        lblOp1.setBackground(new java.awt.Color(51, 51, 51));
        lblOp1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblOp1.setForeground(new java.awt.Color(255, 255, 255));
        lblOp1.setText("Change Password");
        lblOp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOp1.setOpaque(true);
        lblOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOp1MouseExited(evt);
            }
        });

        lblUserLevel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUserLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblUserLevel.setText("jLabel3");

        lblUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("jLabel2");

        lblOp3.setBackground(new java.awt.Color(51, 51, 51));
        lblOp3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblOp3.setForeground(new java.awt.Color(255, 255, 255));
        lblOp3.setText("Log Off");
        lblOp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOp3.setOpaque(true);
        lblOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOp3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOp3MouseExited(evt);
            }
        });

        lblOp2.setBackground(new java.awt.Color(51, 51, 51));
        lblOp2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblOp2.setForeground(new java.awt.Color(255, 255, 255));
        lblOp2.setText("Switch User");
        lblOp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOp2.setOpaque(true);
        lblOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOp2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOp2MouseExited(evt);
            }
        });

        lblOp5.setBackground(new java.awt.Color(51, 51, 51));
        lblOp5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblOp5.setForeground(new java.awt.Color(255, 255, 255));
        lblOp5.setText("Settings");
        lblOp5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOp5.setOpaque(true);
        lblOp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOp5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOp5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOp5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblUserLevel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOp2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lblOp3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lblOp4, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lblOp5, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblUsername)
                        .addGap(18, 18, 18)
                        .addComponent(lblUserLevel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOp3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp4MouseClicked
        
        userManagment mng = new userManagment();
        Home.jDesktopPane2.add(mng);
        mng.setVisible(true);
        
        Home.jDesktopPane2.remove(Home.usermenu);
        Home.jDesktopPane2.repaint();
        lblOp4MouseExited(evt);

    }//GEN-LAST:event_lblOp4MouseClicked

    private void lblOp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp4MouseEntered
        
        lblOp4.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_lblOp4MouseEntered

    private void lblOp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp4MouseExited
        
        lblOp4.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblOp4MouseExited

    private void lblOp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp1MouseEntered
        
        lblOp1.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_lblOp1MouseEntered

    private void lblOp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp1MouseExited
        
        lblOp1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblOp1MouseExited

    private void lblOp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp3MouseEntered
        
        lblOp3.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_lblOp3MouseEntered

    private void lblOp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp3MouseExited
        
        lblOp3.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblOp3MouseExited

    private void lblOp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp2MouseEntered
        
        lblOp2.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_lblOp2MouseEntered

    private void lblOp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp2MouseExited
        
        lblOp2.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_lblOp2MouseExited

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        
        ImageIcon ii = new ImageIcon(getClass().getResource("/images/desktop/user.png"));
        lblUser.setIcon(ii);
        lblUser.setOpaque(false);
        this.dispose();
        Home.userCount = 1;
    }//GEN-LAST:event_formFocusLost

    private void lblOp5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp5MouseEntered
        
        lblOp5.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_lblOp5MouseEntered

    private void lblOp5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp5MouseExited
        
        lblOp5.setBackground(new Color(51, 51, 51));        
    }//GEN-LAST:event_lblOp5MouseExited

    private void lblOp5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp5MouseClicked

//        new Settings().setVisible(true);
        Settings setting = new Settings();
        Home.jDesktopPane2.add(setting);
        setting.setVisible(true);
        lblOp5MouseExited(evt);
    }//GEN-LAST:event_lblOp5MouseClicked

    private void lblOp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp1MouseClicked
        
        changePassword change = new changePassword();
        Home.jDesktopPane2.add(change);
        change.setVisible(true);
        lblOp1MouseExited(evt);
    }//GEN-LAST:event_lblOp1MouseClicked

    private void lblOp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp3MouseClicked

        this.setVisible(false);
        Home home = (Home) Home.users.get(lblUsername.getText());
        home.setVisible(false);
        login.count=0;
        Home.users.remove(lblUsername.getText());
        BuildPC.log.setVisible(true);
        login.loginOpen();
        System.gc();
        lblOp3MouseExited(evt);
        
    }//GEN-LAST:event_lblOp3MouseClicked

    private void lblOp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOp2MouseClicked

        Home home = (Home) Home.users.get(lblUsername.getText());
        home.setVisible(false);
        login.count=0;
        BuildPC.log.setVisible(true);
        login.loginOpen();
        lblOp2MouseExited(evt);
    }//GEN-LAST:event_lblOp2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblOp1;
    private javax.swing.JLabel lblOp2;
    private javax.swing.JLabel lblOp3;
    private javax.swing.JLabel lblOp4;
    private javax.swing.JLabel lblOp5;
    public static javax.swing.JLabel lblUserImage;
    public static javax.swing.JLabel lblUserLevel;
    public static javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
