/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SAM
 */
public class old_invoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form old_invoice
     */
        static int openFrameCount = 0;
        static final int xOffset = 30, yOffset = 30;
        
    public old_invoice() {
        super("Invoice" + (++openFrameCount), 
              true, //resizable
              true, //closable
              true, //maximizable
              true);//iconifiable

        //...Create the GUI and put it in the window...

        //...Then set the window size or call pack...
        setSize(300,300);

        //Set the window's location.
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_invoiceno = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        txt_rep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cusid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_reason = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_method = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        txt_balance = new javax.swing.JTextField();
        txt_nettotal = new javax.swing.JTextField();
        txt_discount = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sales - Invoice");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 144, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Invoice No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 120, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Rep ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 80, -1));

        txt_invoiceno.setEditable(false);
        txt_invoiceno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_invoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 120, 172, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, 172, -1));

        txt_rep.setEditable(false);
        txt_rep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 172, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Customer:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Costomer ID / Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Method");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txt_cusid.setEditable(false);
        txt_cusid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_cusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cusidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 172, -1));

        jPanel2.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ", "Item Description", "Qty", "Unit Price", "Amount", "Discount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 220, -1, 360));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/bad_decision-32.png"))); // NOI18N
        jButton3.setText("Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setText("Reason:");

        txt_reason.setColumns(20);
        txt_reason.setRows(5);
        jScrollPane2.setViewportView(txt_reason);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "To Stock", "To Supplier" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("Qty:");

        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Return:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/disapprove-32.png"))); // NOI18N
        jButton1.setText("Cancel ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/approve-32.png"))); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("BuildPC Computer Systems");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 650, -1));

        txt_method.setEditable(false);
        txt_method.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 172, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/buildPcLogo.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 270, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Payment   Rs");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 610, 160, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Balance     Rs");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 650, 170, -1));

        txt_payment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_payment.setText("0");
        txt_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_paymentKeyTyped(evt);
            }
        });
        jPanel1.add(txt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 610, 240, -1));

        txt_balance.setEditable(false);
        txt_balance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_balance.setText("0");
        jPanel1.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 650, 240, -1));

        txt_nettotal.setEditable(false);
        txt_nettotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nettotal.setText("0");
        txt_nettotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nettotalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nettotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, 172, -1));

        txt_discount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_discount.setText("0");
        txt_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_discountActionPerformed(evt);
            }
        });
        txt_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_discountKeyTyped(evt);
            }
        });
        jPanel1.add(txt_discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 172, -1));

        txt_subtotal.setEditable(false);
        txt_subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_subtotal.setText("0");
        jPanel1.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 172, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Sub Total  Rs");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Discount   Rs");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 120, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Net Total  Rs");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 670, 110, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void oldinvoice(String id){
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        
                    int rowcount=jTable1.getRowCount();
        
                    for (int i = 0; i <rowcount; i++) {
                     dtm.removeRow(0);
                    }
        try {
            ResultSet r = new JDBC().getData("SELECT sk.*,it.* FROM invoice_info AS sk,invoice AS it where  sk.invoice_no = it.invoice_no AND sk.invoice_no LIKE'"+id+"'");
            while(r.next()){
                Vector v=new Vector();
                v.add(r.getString("item_id"));
                v.add(r.getString("item_description")); 
                v.add(r.getString("qty_new")); 
                v.add(r.getDouble("unit_price"));
                double amount=r.getDouble("qty_new")*r.getDouble("unit_price");
                v.add(4, amount);
                v.add(5, r.getDouble("discount"));
                v.add(6, r.getString("status"));
                dtm.addRow(v);
                
                txt_invoiceno.setText(r.getString("invoice_no"));
                txt_rep.setText(r.getString("rep_id"));
                jTextField2.setText(r.getString("date_time"));
                txt_cusid.setText(r.getString("customer_id"));
                txt_method.setText(r.getString("method"));
                
                txt_payment.setText(r.getString("payment"));
                
                int  rows = jTable1.getRowCount();
                
        double total=0;
        for (int i = 0;  i < rows; i++) 
 
        {total += ( Double.parseDouble(jTable1.getValueAt(i, 4).toString())) ;}
        
        String s=total+"";
        txt_subtotal.setText(s);
        
        double discount=0;
        for (int i = 0;  i < rows; i++) 
 
        {discount += ( Double.parseDouble(jTable1.getValueAt(i, 5).toString())) ;}
        
        String s1=discount+"";
        txt_discount.setText(s1);
        
        double nettotal=total-discount;
        String s2=nettotal+"";
        txt_nettotal.setText(s2);
        
        double d=Double.parseDouble(txt_payment.getText());
        double d1=d-nettotal;
        String s3=d1+"";
        txt_balance.setText(s3);
      
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void txt_cusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cusidActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        int i=jTable1.getSelectedRow();
        String s=jTable1.getValueAt(i, 0).toString();
        
        jTextField3.setText(s);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int i1=JOptionPane.showConfirmDialog(this, "Are you sure about return this ITEM....?");
        if(i1==0){
            
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        int i=jTable1.getSelectedRow();
        String s1=jTable1.getValueAt(i, 2).toString();
        String s=jTextField3.getText();
        
        int qty_sold=Integer.parseInt(s1); 
        int qty_return=Integer.parseInt(txt_qty.getText());
        int qty=qty_sold-qty_return;
            
        if(qty_sold>qty_return){
            try {
                new JDBC().putData("update invoice_info set status='"+qty_return+"_returned"+"' where item_id='"+s+"' and invoice_no='"+txt_invoiceno.getText()+"'");
                JOptionPane.showMessageDialog(this, "Returned!");
                
                if(jComboBox2.getSelectedItem()=="To Stock"){
                    ResultSet r = new JDBC().getData("SELECT * from stock where serial='"+s+"'");
                        while(r.next()){
                        int qty_stock=Integer.parseInt(r.getString("qty"));
                        int new_qty=qty_stock+qty_return;
                            new JDBC().putData("update stock set qty='"+new_qty+"' where serial='"+s+"'");
                            JOptionPane.showMessageDialog(this, "Stock Updated.....");
                        }
                }
                try {
                    ResultSet r=new JDBC().getData("SELECT COUNT(return_id) AS row_count FROM returns");
                    while(r.next()){
                    int row=Integer.parseInt(r.getString("row_count"));
                    int return_id=row+1;
                    new JDBC().putData("INSERT INTO returns VALUES('"+return_id+"','"+s+"','"+txt_invoiceno.getText()+"','"+qty_return+"','"+getSupId(s)+"','"+new SimpleDateFormat("yyyy-MM-dd hh:mm:ss").format(new Date())+"','"+jComboBox2.getSelectedItem()+"','"+txt_reason.getText()+"')");
                }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error in retutn table.....");
                }
                
        } catch (Exception e) {
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Can't Return!"
                        + "Check again.....");
        }
        }else{JOptionPane.showMessageDialog(this, "Wrong return!");}
            oldinvoice(txt_invoiceno.getText());
            
        }
        
      
    }//GEN-LAST:event_jButton3ActionPerformed
    
    void rep(){
        try {
            String reportSourse="src\\reports\\invoice.jrxml";
            java.util.Map<String, Object> params=new HashMap<String, Object>();
            params.put("item serial", txt_invoiceno.getText());
            JasperReport jReport=JasperCompileManager.compileReport(reportSourse);
            JasperPrint jp=JasperFillManager.fillReport(jReport, params, new JDBC().con());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rep();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=JOptionPane.showConfirmDialog(this, "Are you sure about cancel this INVOICE....?");
        if(i==0){
            try {
                new JDBC().putData("update invoice set status='"+"Canceled"+"' where invoice_no='"+txt_invoiceno.getText()+"'");
                JOptionPane.showMessageDialog(this, "Invoice Canceled.....");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_paymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentKeyTyped
        char c=evt.getKeyChar();
        if(Character.isAlphabetic(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_paymentKeyTyped

    private void txt_nettotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nettotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nettotalActionPerformed

    private void txt_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_discountActionPerformed

    private void txt_discountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_discountKeyTyped
        char c=evt.getKeyChar();
        if(Character.isAlphabetic(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_discountKeyTyped

    
    String getSupId(String serial){
        String id="SUP000001";
        try {
            ResultSet r = new JDBC().getData(" select sup_id from suppliers where sup_id IN(select sup_id from grn_info where grn_no IN(select grn_no from grn where serial='"+serial+"'))");
            if (r.next()) {
                id = r.getString("sup_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
            return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_cusid;
    private javax.swing.JTextField txt_discount;
    private javax.swing.JTextField txt_invoiceno;
    private javax.swing.JTextField txt_method;
    private javax.swing.JTextField txt_nettotal;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextArea txt_reason;
    private javax.swing.JTextField txt_rep;
    private javax.swing.JTextField txt_subtotal;
    // End of variables declaration//GEN-END:variables
}
