/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thusitha
 */
public class suppaySummary extends javax.swing.JInternalFrame {

    /**
     * Creates new form suppaySummary
     */
    public suppaySummary() {
        super("Supplier Payments Summary", false, true, false, false);
        initComponents();
    }

    public suppaySummary(String supId,String grnNo) {
        this();
        initComponents();
        getSupplierDetails(supId,grnNo);

    }

    public void getSupplierDetails(String supId,String grnNo) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getRowCount();
        for (int j = 0; j < i; j++) {
            dtm.removeRow(0);
        }
        
        Vector sup = new Vector();
        Vector grn = new Vector();
        grn.add("All");
        try {
            ResultSet r2 = new JDBC().getData("SELECT distinct(supid) FROM suppay ");
            while(r2.next()){
                sup.add(r2.getString("supid"));
            }
            cmbboxSupId.setModel(new DefaultComboBoxModel(sup));
            cmbboxGrn.setSelectedItem(supId);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            ResultSet r3 = new JDBC().getData("SELECT distinct(sp.grnNo) FROM suppliers s,suppay sp WHERE s.sup_id=sp.supId AND sp.supId='"+supId+"'");
            while (r3.next()) {
                grn.add(r3.getString("grnNo"));                
                
            }
            cmbboxGrn.setModel(new DefaultComboBoxModel(grn));
            cmbboxGrn.setSelectedIndex(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        try {
            ResultSet r=null;
            if (grnNo.equals("")) {
                r= new JDBC().getData("SELECT * FROM suppliers s,suppay sp WHERE s.sup_id = sp.supid and sp.supid='"+supId+"'");
            }else{ 
                r= new JDBC().getData("SELECT * FROM suppliers s,suppay sp WHERE s.sup_id = sp.supid and sp.supid='"+supId+"' and sp.grnNo='"+grnNo+"'");
                cmbboxGrn.setSelectedItem(grnNo);
                                
            }
            while (r.next()) {
                lblSupName.setText(r.getString("sup_name"));
                lblSupMobi.setText(r.getString("sup_mobile"));
                lblSupEmail.setText(r.getString("sup_email"));
                cmbboxSupId.setSelectedItem(r.getString("supid"));
                Vector v = new Vector();
                v.add(r.getString("payNo"));
                v.add(r.getString("grnNo"));
                v.add(r.getString("date"));
                v.add(r.getString("type"));
                v.add(r.getString("amount"));
                dtm.addRow(v);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/images/background.png"));
                    image = ii.getImage();
                }catch(Exception e){

                }
            }
            @Override
            protected void paintComponent(Graphics graphics){
                super.paintComponent(graphics);
                graphics.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbboxSupId = new javax.swing.JComboBox();
        cmbboxGrn = new javax.swing.JComboBox();
        lblSupName = new javax.swing.JLabel();
        lblSupMobi = new javax.swing.JLabel();
        lblSupEmail = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Supplier Payments Summary");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Supplier ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Supplier Name");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment No", "GRN No", "Date", "Type", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mobile Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("E-Mail Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("GRN No");

        cmbboxSupId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cmbboxGrn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbboxGrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxGrnActionPerformed(evt);
            }
        });

        lblSupName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSupName.setText("jLabel7");

        lblSupMobi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSupMobi.setText("jLabel8");

        lblSupEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSupEmail.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbboxGrn, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE)
                                        .addComponent(cmbboxSupId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(140, 140, 140))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lblSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSupMobi, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(lblSupEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbboxSupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupName)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupMobi)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupEmail)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbboxGrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbboxGrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxGrnActionPerformed

        if (cmbboxGrn.getSelectedIndex()==0) {
            getSupplierDetails(cmbboxSupId.getSelectedItem().toString(), "");
        }else{
            getSupplierDetails(cmbboxSupId.getSelectedItem().toString(), cmbboxGrn.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbboxGrnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbboxGrn;
    private javax.swing.JComboBox cmbboxSupId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSupEmail;
    private javax.swing.JLabel lblSupMobi;
    private javax.swing.JLabel lblSupName;
    // End of variables declaration//GEN-END:variables
}
