/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deeptha Senanayake
 */
public class ViewItems extends javax.swing.JInternalFrame {

    boolean view_grn =false;
    /**
     * Creates new form ViewProducts
     */
    public ViewItems() {
        super("View Product",true,true,true,true);
        initComponents();
        getAllItems(null);
        
    }
    
    void clearTable(JTable table){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int rows =table.getRowCount();
        for (int i = 0; i < rows; i++) {
            model.removeRow(0);
        }
    }
    
    void setTableContent(JTable table,Vector vector){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(vector);
    }
    
    private void getAllItems(String keyword){
        
        int rowCount = table_viewItems.getRowCount();
        DefaultTableModel model1  = (DefaultTableModel) table_viewItems.getModel();
        for (int i = 0; i < rowCount; i++) {
            model1.removeRow(0);
        }
            try {
                String sql="";
                if (keyword!=null) {
                    sql=" where item_des LIKE ('"+keyword+"%') ";
                }
                
                ResultSet r = new JDBC().getData("SELECT * from items "+sql+" ORDER BY(item_id)");
                while (r.next()) {
                    Vector v = new Vector();
                    v.add(r.getString("item_id"));
                    v.add(r.getString("item_model"));
                    v.add(r.getString("item_cate"));
                    v.add(r.getString("item_des"));
                    model1.addRow(v);
                }
            }catch(Exception e){
                e.printStackTrace();
            } 
            System.gc();
        }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
 regenerated by the Form ItemsEditor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_refresh = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_avail = new javax.swing.JLabel();
        txt_returns = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_viewItems = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_invoice = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_grn = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tag-32.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1366, 731));
        setMinimumSize(new java.awt.Dimension(1366, 731));
        setPreferredSize(new java.awt.Dimension(1366, 731));
        getContentPane().setLayout(null);

        btn_refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sinchronize-32.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh);
        btn_refresh.setBounds(10, 649, 115, 41);

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tag-64.png"))); // NOI18N
        jLabel38.setText("View Item Details");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel38);
        jLabel38.setBounds(10, 11, 325, 64);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Availability :");

        txt_avail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_returns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_returns.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_returnsMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Returns :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_avail, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(txt_returns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_avail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_returns, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1001, 555, 339, 82);

        table_viewItems.setAutoCreateRowSorter(true);
        table_viewItems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_viewItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Model", "Item Category", "Item Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_viewItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_viewItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_viewItemsMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_viewItems);
        if (table_viewItems.getColumnModel().getColumnCount() > 0) {
            table_viewItems.getColumnModel().getColumn(0).setMinWidth(100);
            table_viewItems.getColumnModel().getColumn(0).setPreferredWidth(100);
            table_viewItems.getColumnModel().getColumn(0).setMaxWidth(200);
            table_viewItems.getColumnModel().getColumn(1).setMinWidth(200);
            table_viewItems.getColumnModel().getColumn(1).setPreferredWidth(200);
            table_viewItems.getColumnModel().getColumn(1).setMaxWidth(250);
            table_viewItems.getColumnModel().getColumn(2).setMinWidth(200);
            table_viewItems.getColumnModel().getColumn(2).setPreferredWidth(250);
            table_viewItems.getColumnModel().getColumn(2).setMaxWidth(300);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 127, 985, 510);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Issued Invoices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);

        table_invoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Invoice No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_invoiceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_invoice);
        if (table_invoice.getColumnModel().getColumnCount() > 0) {
            table_invoice.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1001, 86, 339, 220);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GRN Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setOpaque(false);

        table_grn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_grn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "GRN No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_grn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_grnMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_grnMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(table_grn);
        if (table_grn.getColumnModel().getColumnCount() > 0) {
            table_grn.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(1001, 317, 339, 220);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_image-32.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(131, 649, 91, 41);

        jPanel2.setOpaque(false);

        btn_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 580, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1350, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed

       getAllItems(null);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    DefaultTableModel getNewModel (JTable table){
        return (DefaultTableModel) table.getModel();
    }
    void ClearTables(){
        int rows = table_grn.getRowCount();
        int rows1 = table_invoice.getRowCount();
        for (int i = 0; i < rows; i++) {
            getNewModel(table_grn).removeRow(0);
        }
        for (int i = 0; i < rows1; i++) {
            getNewModel(table_invoice).removeRow(0);
        }
    }
    private void table_viewItemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_viewItemsMouseReleased

        try {
            int sel = table_viewItems.getSelectedRow(),qty=0,sold=0,returns=0;
            ClearTables();
            JDBC Data = new JDBC();
            ResultSet r  = Data.getData("SELECT qty FROM stock WHERE item_id='"+table_viewItems.getValueAt(sel, 0)+"' ");
            ResultSet r2 = Data.getData("SELECT grn_no,date FROM grn_info WHERE grn_no IN(SELECT grn_no FROM grn WHERE item_id='"+table_viewItems.getValueAt(sel, 0)+"') ");
            ResultSet r3 = Data.getData("SELECT qty FROM returns WHERE serial IN(SELECT serial FROM stock WHERE item_id='"+table_viewItems.getValueAt(sel, 0)+"')");
            while(r3.next()){
                returns+=r3.getInt("qty");
            }
            while(r2.next()){
                Vector v = new Vector();
                v.add(r2.getString("date"));
                v.add(r2.getString("grn_no"));
                
                getNewModel(table_grn).addRow(v);
            }
            while (r.next()) {                
                qty +=r.getInt("qty");
            }
            ResultSet soldCount = Data.getData("SELECT qty_new FROM invoice_info WHERE item_id='"+table_viewItems.getValueAt(sel, 0)+"' ");
            while (soldCount.next()) {                
                sold+=soldCount.getInt("qty");
            }
            if (qty>0) {
                txt_avail.setText(qty+" Available/"+sold+" Sold");
                txt_avail.setForeground(new Color(0,102,0));
            }else{
                txt_avail.setText("Not Available/"+sold+" Sold");
                txt_avail.setForeground(new Color(204,0,51));            
            }
            
            if (returns>0) {
                txt_returns.setText(returns+" Returns");
                txt_returns.setToolTipText(returns+" Returns from this item");
            } else {
                txt_returns.setText("No Returns");
                txt_returns.setToolTipText("No Returns from this item");
            }
            
            clearTable(table_invoice);
            ResultSet invoices = Data.getData("SELECT date_time,invoice_no FROM invoice where invoice_no IN(SELECT invoice_no FROM invoice_info WHERE item_id IN(select serial from stock where item_id IN('"+table_viewItems.getValueAt(sel, 0)+"') ))");
            while (invoices.next()) {                
                Vector inv = new Vector();
                String date = new SimpleDateFormat("yyyy-MM-dd").format(invoices.getDate("date_time"));
                inv.add(date);
                inv.add(invoices.getString("invoice_no"));
                setTableContent(table_invoice, inv);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.gc();
    }//GEN-LAST:event_table_viewItemsMouseReleased

    private void txt_returnsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_returnsMouseReleased

        if (view_grn) {
            
        }
    }//GEN-LAST:event_txt_returnsMouseReleased

    private void table_grnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_grnMouseReleased
       
        
    }//GEN-LAST:event_table_grnMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (table_viewItems.getSelectedRowCount()>0) {
            int sel = table_viewItems.getSelectedRow();
            ItemsEditor editor = new ItemsEditor();
            editor.setDetails(table_viewItems.getValueAt(sel, 0).toString(), table_viewItems.getValueAt(sel, 1).toString(), table_viewItems.getValueAt(sel, 2).toString(), table_viewItems.getValueAt(sel, 3).toString());
            editor.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Please Select item to Edit !","Editor",0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        getAllItems(txt_search.getText());
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped

        getAllItems(txt_search.getText());
    }//GEN-LAST:event_txt_searchKeyTyped

    private void table_grnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_grnMouseClicked

        if (evt.getClickCount()==2) {
            ViewGRN grn = new ViewGRN();
            Home.jDesktopPane2.add(grn);
            grn.setVisible(true);
            grn.viewByGRN(table_grn.getValueAt(table_grn.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_table_grnMouseClicked

    private void table_invoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_invoiceMouseClicked

        if (evt.getClickCount()==2) {
            String invID = table_invoice.getValueAt(table_invoice.getSelectedRow(), 1).toString();
            Invoice_details inv = new Invoice_details(invID);
            Home.jDesktopPane2.add(inv);
            inv.setVisible(true);
        }
    }//GEN-LAST:event_table_invoiceMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_grn;
    private javax.swing.JTable table_invoice;
    public static javax.swing.JTable table_viewItems;
    private javax.swing.JLabel txt_avail;
    private javax.swing.JLabel txt_returns;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
